'use client';
import {useState} from 'react';
import type {Ga4Report} from '../../lib/hub/providers/ga4';
import type {ProviderResult} from '../../lib/hub/providers/common';
const fmt=(n:number)=>new Intl.NumberFormat('nl-NL').format(n);
const month=(s:string)=>new Intl.DateTimeFormat('nl-NL',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${s.slice(0,4)}-${s.slice(4,6)}-01T00:00:00Z`));
export function TrafficCharts({daily,monthly,stale=false}:{daily?:ProviderResult<Ga4Report>;monthly?:ProviderResult<Ga4Report>;stale?:boolean}){
 const rows=daily?.state==='ready'?daily.data?.rows.filter(r=>/^\d{8}$/.test(r.dimensions.date)&&Number.isFinite(r.metrics.totalUsers)).slice(-31)||[]:[];
 const months=monthly?.state==='ready'?monthly.data?.rows.filter(r=>/^\d{6}$/.test(r.dimensions.yearMonth)&&Number.isFinite(r.metrics.totalUsers)).sort((a,b)=>a.dimensions.yearMonth.localeCompare(b.dimensions.yearMonth))||[]:[];
 const [chosenA,setA]=useState(''),[chosenB,setB]=useState('');
 const a=months.find(r=>r.dimensions.yearMonth===chosenA)||months.at(-1),b=months.find(r=>r.dimensions.yearMonth===chosenB)||months.at(-2);
 const max=Math.max(1,...rows.map(r=>r.metrics.totalUsers));
 const points=rows.map((r,i)=>`${35+i*530/Math.max(1,rows.length-1)},${175-r.metrics.totalUsers/max*140}`).join(' ');
 const delta=a&&b? a.metrics.totalUsers-b.metrics.totalUsers:null;
 return <div className="hub-traffic-grid">
 <section className="hub-panel"><p className="hub-kicker">Bezoekersgrafiek</p><h2>Hoe verloopt je bezoek?</h2><p>Gebruikers per gemeten dag · {daily?.period?`${daily.period.startDate} t/m ${daily.period.endDate}`:'nog geen meetperiode'}</p>{rows.length?<><svg viewBox="0 0 600 220" role="img" aria-label="Lijngrafiek van gemeten gebruikers per dag; exacte aantallen in de tabel hieronder"><path d="M35 30V175H570" fill="none" stroke="#cedbd5"/><text x="3" y="38" fontSize="12">{fmt(max)}</text><text x="10" y="178" fontSize="12">0</text><polyline points={points} fill="none" stroke="#184bce" strokeWidth="3" strokeLinejoin="round"/>{rows.map((r,i)=><circle key={r.dimensions.date} cx={35+i*530/Math.max(1,rows.length-1)} cy={175-r.metrics.totalUsers/max*140} r="3" fill="#184bce"><title>{r.dimensions.date}: {fmt(r.metrics.totalUsers)} gebruikers</title></circle>)}<text x="35" y="205" fontSize="12">{rows[0].dimensions.date.slice(6)}-{rows[0].dimensions.date.slice(4,6)}</text><text x="535" y="205" fontSize="12">{rows.at(-1)!.dimensions.date.slice(6)}-{rows.at(-1)!.dimensions.date.slice(4,6)}</text></svg><details><summary>Exacte dagcijfers</summary><div className="hub-table-wrap"><table className="hub-table"><thead><tr><th>Dag</th><th>Gebruikers</th><th>Sessies</th></tr></thead><tbody>{rows.map(r=><tr key={r.dimensions.date}><th>{r.dimensions.date.slice(6)}-{r.dimensions.date.slice(4,6)}-{r.dimensions.date.slice(0,4)}</th><td>{fmt(r.metrics.totalUsers)}</td><td>{fmt(r.metrics.sessions)}</td></tr>)}</tbody></table></div></details></>:<p className="hub-empty">Koppel GA4 en haal een dagrapport op om deze grafiek te vullen.</p>}<p className="hub-note">Bron: GA4. Daggebruikers zijn geen optelbaar uniek periodetotaal. Ontbrekende dagen worden niet als nul ingevuld.{stale?' Oudere gegevens: vernieuw de bron.':''}</p></section>
 <section className="hub-panel"><p className="hub-kicker">Maand naast maand</p><h2>Groeit je bereik?</h2><p>Vergelijk twee afgesloten kalendermaanden. Iedere maand heeft een afzonderlijk gemeten gebruikerstotaal.</p>{a&&b?<><div className="hub-month-select"><label>Maand<select value={a.dimensions.yearMonth} onChange={e=>setA(e.target.value)}>{months.map(r=><option key={r.dimensions.yearMonth} value={r.dimensions.yearMonth}>{month(r.dimensions.yearMonth)}</option>)}</select></label><label>Vergelijk met<select value={b.dimensions.yearMonth} onChange={e=>setB(e.target.value)}>{months.map(r=><option key={r.dimensions.yearMonth} value={r.dimensions.yearMonth}>{month(r.dimensions.yearMonth)}</option>)}</select></label></div><div className="hub-month-bars">{[a,b].map((r,i)=><div key={i}><span>{month(r.dimensions.yearMonth)}</span><strong>{fmt(r.metrics.totalUsers)} <small>gebruikers</small></strong><div><i style={{width:`${r.metrics.totalUsers/Math.max(1,a.metrics.totalUsers,b.metrics.totalUsers)*100}%`}}/></div></div>)}</div><p className="hub-change">{delta!>0?'+':''}{fmt(delta!)} gebruikers{b.metrics.totalUsers>0?` (${delta!>0?'+':''}${(delta!/b.metrics.totalUsers*100).toLocaleString('nl-NL',{maximumFractionDigits:1})}%)`:' · procentuele verandering niet berekenbaar vanaf nul'}</p><p>Sessies: {fmt(a.metrics.sessions)} tegenover {fmt(b.metrics.sessions)}. Paginaweergaven: {fmt(a.metrics.screenPageViews)} tegenover {fmt(b.metrics.screenPageViews)}.</p></>:<p className="hub-empty">Er zijn nog geen twee gemeten maanden beschikbaar. Ontbrekende historie wordt niet aangevuld met verzonnen aantallen.</p>}<p className="hub-note">Bron: GA4 · {monthly?.timeZone||'tijdzone nog onbekend'}. Laatste zes afgesloten maanden; aantallen zijn niet gecorrigeerd voor het aantal dagen. {monthly?.warnings.join(' ')}</p></section>
 </div>;
}
