import {speedMetrics,type SpeedResult} from '../../../lib/speed-test';
export function SpeedReport({result}:{result:SpeedResult}){return <div className="speed-report-detail">
      <div className="speed-result-heading"><div><span className="eyebrow">Lighthouse · {result.device==='mobile'?'mobiele':'desktop'} labtest</span><h4>Dit laat jouw meting zien.</h4><p className="speed-result-url">{result.finalUrl}</p>{result.finalUrl!==result.requestedUrl&&<p className="speed-note">Ingevoerd: {result.requestedUrl}. Google heeft een ander eindadres gemeten.</p>}</div>
        <div className={`speed-score ${result.score>=90?'speed-good':result.score>=50?'speed-medium':'speed-poor'}`}><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="52"/><circle cx="60" cy="60" r="52" pathLength="100" strokeDasharray={`${result.score} 100`} transform="rotate(-90 60 60)"/></svg><strong>{result.score}<small>/ 100</small></strong><span>Prestaties</span></div>
      </div>
      <p className="speed-note">Gemeten op {new Date(result.fetchTime).toLocaleString('nl-NL',{timeZone:'Europe/Amsterdam'})} (Amsterdam) · Lighthouse {result.version||'versie niet doorgegeven'}. Eén pagina, één meetmoment. <a target="_blank" rel="noopener noreferrer" href="/tools/snelheidstest/pagespeed-score">Zo lees je de prestatiescore (nieuw tabblad)</a>.</p>
      {result.warnings.length>0&&<aside className="speed-warning"><h3>Beperkingen bij deze meting</h3><ul>{result.warnings.map((warning,i)=><li key={i}>{warning}</li>)}</ul></aside>}
      <div className="speed-metrics">{speedMetrics.map(metric=>{const measured=result.metrics.find(item=>item.id===metric.id);return <article key={metric.id}><span>{metric.short}</span><h3>{metric.label}</h3><strong>{measured?.displayValue??'Niet ontvangen'}</strong><p>{metric.explanation}</p></article>;})}</div>
      <div className="speed-result-context"><h3>Van cijfer naar oorzaak</h3><p>De prestatiescore combineert deze laadmetingen met verschillende gewichten. Een laag cijfer wijst niet vanzelf één bestand aan. Gebruik de onderstaande bevindingen voor je volgende stap.</p><p>Deze test meet geen INP van echte bezoekers. Daarvoor zijn andere gegevens nodig. Lees het <a target="_blank" rel="noopener noreferrer" href="/tools/snelheidstest/core-web-vitals">verschil tussen een labtest en Core Web Vitals (nieuw tabblad)</a>.</p></div>
      <h3 className="speed-section-title">Aandachtspunten uit deze meting <span>{result.findings.length}</span></h3>
      {result.findings.length?result.findings.map((finding,index)=><details className="speed-finding" key={finding.id} open={index===0}><summary>{finding.title}</summary><p><b>Gevonden:</b> {finding.what}</p><p>{finding.why}</p><p><b>Volgende stap:</b> {finding.action}</p>{finding.evidence?.length?<div className="speed-evidence"><h4>Voorbeelden uit het rapport</h4>{finding.evidence.map((e,i)=><pre key={i}>{e}</pre>)}</div>:<p className="speed-note">Google gaf bij deze bevinding geen bestands- of codevoorbeeld mee.</p>}</details>):<p>Er zijn geen aanvullende aandachtspunten uit de ontvangen prestatie-audits gehaald. Controleer ook de laadmetingen en eventuele waarschuwingen. Dit bewijst niet dat er nergens iets te verbeteren is.</p>}
      <details className="speed-passed"><summary>Wat ging goed in deze test? ({result.passed.length})</summary>{result.passed.length?<ul>{result.passed.map(item=><li key={item.id}><strong>{item.title}</strong><p>{item.description}</p>{item.evidence.map((e,i)=><pre key={i}>{e}</pre>)}</li>)}</ul>:<p>Geen afzonderlijke geslaagde prestatiecontroles meegegeven.</p>}</details>
      <p className="speed-note">Meet na een gerichte aanpassing opnieuw met dezelfde URL en apparaatkeuze. Geschatte tijdwinst uit verschillende audits kun je niet zomaar bij elkaar optellen.</p>

</div>;}

export function SpeedComparison({states}:{states:Partial<Record<'mobile'|'desktop',import('../../../lib/speed-report').SpeedState>>}){return <table className="speed-comparison-table"><caption>De metingen naast elkaar. Eerdere resultaten zijn gemarkeerd.</caption><thead><tr><th scope="col">Meting</th>{(['mobile','desktop'] as const).map(kind=><th scope="col" key={kind}>{kind==='mobile'?'Mobiel':'Desktop'}{states[kind]?.result&&states[kind]?.status!=='success'&&<small> (eerder)</small>}</th>)}</tr></thead><tbody><tr><th scope="row">Score</th>{(['mobile','desktop'] as const).map(kind=><td key={kind}>{states[kind]?.result?.score??'Onbekend'}</td>)}</tr>{speedMetrics.map(metric=><tr key={metric.id}><th scope="row"><abbr title={metric.label}>{metric.short}</abbr></th>{(['mobile','desktop'] as const).map(kind=><td key={kind}>{states[kind]?.result?.metrics.find(m=>m.id===metric.id)?.displayValue??'Onbekend'}</td>)}</tr>)}</tbody></table>;}
