import { PageHero } from '../studio-components';
import { Arrow, Eyebrow, PriceCards, Cta } from '../ui';
import { Breadcrumbs, withPageMetadata, JsonLd } from '../seo';
import { BeurswijzerScreen } from '../beurswijzer-screen';
import { site } from '../site-data';
import '../regional.css';

export const metadata = withPageMetadata({}, '/webdesign-venlo');

function ScopeSketch({ index }: { index: number }) {
  return <div className={`regional-sketch regional-sketch-${index}`} aria-hidden="true">
    <span className="regional-sketch-orbit"/>
    <div className="regional-sketch-sheet regional-sketch-back"><span/><i/><i/></div>
    <div className="regional-sketch-sheet regional-sketch-front">
      <div className="regional-sketch-bar"><b>jouw bedrijf</b><span>•••</span></div>
      <div className="regional-sketch-content"><strong>{['Eén pagina.\nJouw verhaal.', 'Elke dienst\neen eigen plek.', 'Jouw idee.\nMeer mogelijk.'][index]}</strong><span className="regional-sketch-shape"/><i/><i/><span className="regional-sketch-button">{['Maak kennis ↗', 'Ontdek ons werk ↗', 'Bekijk je overzicht ↗'][index]}</span></div>
    </div>
    <div className="regional-sketch-detail">{index === 0 ? <><b>↓</b><span>Aanbod<br/>Werk<br/>Contact</span></> : index === 1 ? <><span>01 / Je aanbod</span><span>02 / Je werk</span><span>03 / Over jou</span></> : <><b>Alles verbonden</b><span>Website <i>↔</i> Jouw tools</span><span className="regional-sketch-chart"><i/><i/><i/><i/></span></>}</div>
    <span className="regional-sketch-caption">{['Van kennismaken naar contact', 'Ruimte voor ieder onderwerp', 'Inhoud en functies, samen'][index]}</span>
  </div>;
}

const questions = [
  ['Wat kost een website laten maken in Venlo?', 'De omvang bepaalt je vertrekpunt: een onepager kost €1.082,95 inclusief btw (€895 exclusief), vijf pagina’s €2.292,95 inclusief btw (€1.895 exclusief) en maatwerk begint bij €3.327,50 inclusief btw (€2.750 exclusief). Daarbij hoort hosting vanaf €6,05 inclusief btw per maand, minimaal twaalf maanden. Extra functies of pagina’s stemmen we vooraf af. Je hoeft niet voor maatwerk te kiezen alleen omdat je wensen nog niet helemaal duidelijk zijn.'],
  ['Heeft Sitesnit een kantoor in Venlo?', 'Sitesnit werkt vanuit Baarlo voor ondernemers in Venlo en de rest van Limburg. Wil je kennismaken? Vraag een belafspraak aan en geef optioneel een voorkeursdag door. Een bezoekadres of kantoor in Venlo is geen onderdeel van dit aanbod.'],
  ['Moet ik al teksten, foto’s en een huisstijl hebben?', 'Nee. We bekijken eerst wat beschikbaar is en welke inhoud ontbreekt. Daarna spreken we af wat jij aanlevert en wat Sitesnit uitwerkt. Eigen beelden, heldere teksten en een herkenbaar ontwerp krijgen ieder een passende plek in het voorstel.'],
  ['Kan mijn bestaande website beter zonder opnieuw te beginnen?', 'Dat kan, afhankelijk van de inhoud en technische basis. De websitecheck brengt antwoorden over je klantpad samen met een mobiele Lighthouse-meting van één pagina. Die uitkomst helpt om gerichte verbeteringen of een herontwerp te bespreken.'],
  ['Wordt mijn website ook vindbaar in Google?', 'Een duidelijke paginastructuur, bruikbare inhoud en een verzorgde technische basis ondersteunen vindbaarheid. De uiteindelijke zichtbaarheid hangt ook af van de zoekvraag, concurrentie en wat er na oplevering gebeurt. Een specifieke positie wordt niet beloofd.'],
];

export default function VenloPage() {
  return <>
    <Breadcrumbs items={[{name:'Home',path:'/'},{name:'Webdesign Venlo',path:'/webdesign-venlo'}]}/>
    <JsonLd data={{'@context':'https://schema.org','@type':'Service','@id':`${site.origin}/webdesign-venlo#service`,name:'Website laten maken voor ondernemers in Venlo',serviceType:'Webdesign en websiteontwikkeling',url:`${site.origin}/webdesign-venlo`,provider:{'@id':`${site.origin}/#organization`},areaServed:{'@type':'City',name:'Venlo'},hasOfferCatalog:{'@id':`${site.origin}/kosten#websitepakketten`}}}/>
    <PageHero eyebrow="Voor ondernemers in Venlo / Vanuit Baarlo" title="Website laten maken" accent="in Venlo." description="Je bedrijf verdient een website die laat zien wat je doet en bezoekers helpt de volgende stap te zetten. Sitesnit brengt je aanbod, ontwerp en techniek samen — met net zoveel aandacht voor de telefoon als voor het grote scherm." tone="green" visual={<aside className="regional-hero-art" aria-label="Sitesnit werkt vanuit Baarlo voor ondernemers in Venlo"><span>Jouw bedrijf → Jouw website</span><strong>Een eigen gezicht.<br/>Een duidelijk verhaal.</strong><div className="regional-panel"><span>sitesnit <i>↗</i></span><p>Ontwerp.<br/>Inhoud.<br/><b>Samenhang.</b></p><div><i/><i/><i/></div></div><p>Vanuit Baarlo. Voor jouw plannen.</p></aside>}><a className="button" href="/contact?dienst=webdesign">Bespreek je website <Arrow/></a><a className="text-link" href="#prijzen-venlo">Bekijk je investering ↓</a></PageHero>
    <section className="wrap regional-fit" id="mogelijkheden-venlo"><div><Eyebrow>Wat heeft je bedrijf nodig?</Eyebrow><h2>Je inhoud bepaalt<br/><em>hoe groot we beginnen.</em></h2></div><div>{[
      ['Eén helder aanbod', 'Voor een zelfstandige of een bedrijf met een compact verhaal kan één pagina genoeg zijn. Aanbod, voorbeelden en contact volgen elkaar logisch op.'],
      ['Meerdere diensten of doelgroepen', 'Met aparte pagina’s geef je ieder onderwerp eigen uitleg. Bezoekers kunnen direct landen bij de dienst die ze zoeken, zonder door een heel ander verhaal te hoeven.'],
      ['Een website die moet doorgroeien', 'Een eigen rekentool, extra pagina’s of een koppeling vraagt om een bredere verkenning. We maken eerst duidelijk welke functie werkelijk nodig is en welke techniek daarbij past.'],
    ].map(([title,text],i)=><article key={title} data-scroll-scene="unfold"><ScopeSketch index={i}/><div className="regional-fit-copy"><span>0{i+1} / {['Onepager','Website','Maatwerk'][i]}</span><h3>{title}</h3><p>{text}</p><a className="text-link" href={`/diensten/webdesign/pakketten#${['onepager','website','maatwerk'][i]}`}>{['Bekijk de onepager','Bekijk het websitepakket','Ontdek maatwerk'][i]} <Arrow/></a></div></article>)}</div></section>
    <section className="wrap regional-process" id="aanpak-venlo"><div><Eyebrow>Van vraag naar website</Eyebrow><h2>Weten wat we maken.<br/><em>Begrijpen waarom.</em></h2><p>We beginnen met je aanbod en de belangrijkste vragen van je bezoekers. Dat vormt de basis voor de pagina’s, teksten en route naar contact.</p><a className="text-link" href="/diensten/webdesign">Meer over ontwerp en ontwikkeling <Arrow/></a></div><ol data-scroll-scene="unfold"><li data-reveal><span className="regional-step-number" aria-hidden="true">01</span><b>De inhoud scherp</b><p>Welke diensten zijn belangrijk, welk werk kun je laten zien en wat moet iemand begrijpen voordat hij contact opneemt?</p></li><li data-reveal><span className="regional-step-number" aria-hidden="true">02</span><b>Een herkenbaar ontwerp</b><p>Typografie, kleuren, beelden en beweging ondersteunen je verhaal. We ontwerpen de mobiele indeling bewust, zodat lezen en kiezen eenvoudig blijven.</p></li><li data-reveal><span className="regional-step-number" aria-hidden="true">03</span><b>Techniek die past</b><p>We bouwen de afgesproken pagina’s en functies en controleren de routes en formulieren. Specifieke koppelingen en aanvullingen leggen we vast in het voorstel.</p></li></ol></section>
    <section className="wrap regional-proof" id="werk-venlo"><div className="regional-proof-screen" role="img" aria-label="HTML-presentatie van de Beurswijzer-homepage"><BeurswijzerScreen/></div><div><Eyebrow>Een voorbeeld van het werk</Eyebrow><h2>Van veel informatie<br/><em>naar een helder platform.</em></h2><p>Voor Beurswijzer komen een eigen visuele identiteit, financiële uitleg en interactieve berekeningen samen. De case laat zien hoe inhoud en techniek op mobiel en desktop hun plek krijgen.</p><p>Bekijk de ontwerpkeuzes, de mobiele indeling en de verbinding tussen lezen en zelf een scenario doorrekenen.</p><a className="text-link" href="/projecten/beurswijzer">Bekijk de Beurswijzer-case <Arrow/></a></div></section>
    <section className="pricing-section" id="prijzen-venlo"><div className="wrap"><Eyebrow>De investering</Eyebrow><h2>Een passend begin.<br/><em>Met duidelijke prijzen.</em></h2><PriceCards compact/><div className="regional-price-context"><p>Een standaardformulier, mobiel ontwerp en enkele verfijnde animaties maken een website niet automatisch maatwerk. De definitieve inhoud en voorwaarden spreken we vooraf af. Hosting, onderhoud en doorlopende content zijn afzonderlijke keuzes.</p><a className="text-link" href="/kosten">Vergelijk de kosten en afspraken <Arrow/></a></div></div></section>
    <section className="wrap regional-collaboration"><div><Eyebrow>Ken je vertrekpunt</Eyebrow><h2>Vernieuwen of verbeteren?</h2><p>Heb je al een website? Je hoeft niet meteen te besluiten om opnieuw te bouwen. Met de websitecheck zie je waar je boodschap, klantpad en technische basis aandacht vragen.</p><a className="text-link" href="/websitecheck">Onderzoek je bestaande website <Arrow/></a></div><div><Eyebrow>Samenwerken vanuit Baarlo</Eyebrow><h2>Een gesprek over jouw plannen.</h2><p>Sitesnit werkt voor ondernemers in Venlo en breder in Limburg, waaronder de omgeving van Baarlo, Maasbree, Kessel en Panningen. Een belafspraak kan op werkdagen tussen 18:00 en 21:30 of in het weekend. Je voorkeursdag doorgeven is optioneel; het moment stemmen we samen af.</p><a className="text-link" href="/contact?dienst=webdesign">Vraag een belafspraak aan <Arrow/></a></div></section>
    <section className="wrap regional-questions" id="vragen-venlo"><Eyebrow>Voor je kiest</Eyebrow><h2>Vragen over je nieuwe website.</h2><div>{questions.map(([question,answer])=><article key={question}><h3>{question}</h3><p>{answer}</p></article>)}</div></section>
    <Cta title="Jouw bedrijf in Venlo." accent="Een website die erbij past."/>
  </>;
}
