import { withPageMetadata, Breadcrumbs } from '../../../seo';
import { PageHero } from "../../../studio-components";
import "../../../expansion.css";
import "../../../service-experience.css";
import { ServiceCanvas } from "../../../service-canvas";
import { Arrow, Eyebrow } from "../../../ui";
import type { Metadata } from "next";
export const metadata:Metadata=withPageMetadata({alternates:{canonical:"/diensten/webdesign/pakketten"}}, '/diensten/webdesign/pakketten');
const packages=[
  {id:"onepager",label:"01 / Eén pagina",title:"Eén verhaal. Eén logische route.",text:"Een onepager bundelt je introductie, aanbod, voorbeelden en contact op één doorlopende pagina. Geschikt wanneer je aanbod compact is en bezoekers geen uitgebreide keuze tussen onderwerpen hoeven te maken.",items:[["De indeling","Een duidelijke introductie, uitleg van je aanbod, ruimte voor bewijs of werk en een contactgedeelte. De navigatie kan naar onderdelen op dezelfde pagina springen."],["Het gebruik","Je bezoeker volgt één samenhangende route. Op mobiel blijft ieder onderdeel overzichtelijk en staat de volgende stap dicht bij de uitleg."],["Wanneer dit past","Bijvoorbeeld voor een zelfstandige, één duidelijke dienst of een compact portfolio. De hoeveelheid en samenhang van je inhoud bepalen of één pagina genoeg ruimte geeft."]]},
  {id:"website",label:"02 / Vijf pagina’s",title:"Meer onderwerpen. Een eigen plek.",text:"Een bedrijfswebsite met vijf afzonderlijke pagina’s geeft je verhaal meer ruimte. Bezoekers kunnen direct naar de informatie die voor hen relevant is, terwijl de pagina’s samen een herkenbaar geheel vormen.",items:[["De indeling","Bijvoorbeeld home, diensten, projecten, over je bedrijf en contact. De precieze verdeling volgt uit je aanbod; deze vijf namen zijn een voorbeeld, geen verplichte indeling."],["Het gebruik","Duidelijke navigatie en interne links verbinden je onderwerpen. Iedere pagina krijgt een eigen introductie, hoofdvraag en logische vervolgstap."],["Wanneer dit past","Voor een bedrijf met meerdere onderwerpen, meer uitleg of werk dat een eigen plek verdient. Als iedere dienst een uitgebreide verdieping nodig heeft, kijken we samen naar de omvang."]]},
  {id:"maatwerk",label:"03 / Volledig maatwerk",title:"Jouw werking. Specifiek gecodeerd.",text:"Soms moet je website meer doen dan informeren. Dan ontwerpen en coderen we de afgesproken werking voor jouw situatie: van een eigen rekentool tot een grotere contentstructuur, klantomgeving of koppeling.",items:[["De indeling","Het aantal pagina’s, schermen en gebruiksstappen volgt uit je doel. We werken de belangrijke routes eerst uit voordat de techniek wordt gebouwd."],["De functies","Denk aan een calculator, filters, dataverwerking, een boekingsproces of API-koppelingen. Invoer, berekeningen, uitkomsten en uitzonderingen worden concreet beschreven en getest."],["Wanneer dit past","Wanneer omvang of werking buiten een compacte bedrijfswebsite valt. Responsive vormgeving, een standaardformulier of subtiele animatie maakt een website op zichzelf niet automatisch maatwerk."]]}
];
export default function Pakketten(){return <>
  <Breadcrumbs items={[{name:'Home',path:'/'},{name:'Diensten',path:'/diensten'},{name:'Webdesign',path:'/diensten/webdesign'},{name:'Websitepakketten',path:'/diensten/webdesign/pakketten'}]}/>
  <PageHero eyebrow="Webdesign / De pakketten uitgelegd" title="De juiste ruimte." accent="Voor jouw verhaal." description="Je hoeft nog geen pakket te kiezen. Lees eerst wat één pagina, vijf pagina’s of volledig maatwerk betekent voor de inhoud en het gebruik van je website. Daarna kun je de investering vergelijken." visual={<ServiceCanvas kind="webdesign"/>}>
    <a className="button" href="/kosten">Vergelijk de kosten <Arrow /></a><a className="text-link" href="/diensten/webdesign">Terug naar webdesign <Arrow /></a>
  </PageHero>
  <nav className="wrap services-intro-links" aria-label="Pakketverdieping"><a href="#onepager">Onepager</a><a href="#website">Vijf pagina’s</a><a href="#maatwerk">Volledig maatwerk</a></nav>
  <div className="wrap package-guide">{packages.map(p=><section id={p.id} className="package-guide-section" key={p.id}><div><Eyebrow>{p.label}</Eyebrow><h2>{p.title}</h2><p>{p.text}</p><a className="text-link" href={`/kosten#${p.id}`}>Bekijk de investering <Arrow /></a></div><dl>{p.items.map(([title,text])=><div key={title} data-reveal><dt>{title}</dt><dd>{text}</dd></div>)}</dl></section>)}</div>
  <section className="wrap service-deep-links"><div><Eyebrow>Het merk eromheen</Eyebrow><h2>Tekst en beeld.<br /><em>Met dezelfde aandacht.</em></h2><p>Logo, kleuren, copywriting en eigen foto’s of video kunnen mee worden ontwikkeld. We leggen per onderdeel vast wat nodig is en wie het verzorgt. Fotografie en video lopen via een externe partner.</p><a className="text-link" href="/diensten/branding">Ontdek merk & identiteit <Arrow /></a></div><div><Eyebrow>Een winkel of platform</Eyebrow><h2>Meer dan<br /><em>pagina’s alleen.</em></h2><p>Een webshop heeft product- en bestelstromen; een platform kan eigen dataverwerking nodig hebben. Die werking bepalen we afzonderlijk, zodat het voorstel bij de echte opdracht past.</p><a className="text-link" href="/diensten/webshops">Bekijk webshops <Arrow /></a><a className="text-link" href="/diensten/webapps">Bekijk webapps & klantportalen <Arrow /></a></div></section>
  <section className="wrap service-investment"><div><Eyebrow>Van uitleg naar een keuze</Eyebrow><h2>Nu weet je wat past.<br /><em>Bekijk de investering.</em></h2><p>Op de kostenpagina staan de pakketprijzen en het vertrekpunt voor maatwerk. Twijfel je nog, dan helpt de prijscheck je wensen ordenen.</p></div><a className="button" href="/kosten">Naar kosten & pakketten <Arrow /></a></section>
</>;}
