import {FaqData} from './seo';
import { ServiceToolRoute } from './service-tool-route';
import type { Service } from "./diensten/service-data";
import { Arrow, Eyebrow } from "./ui";
import { ServiceCanvas } from "./service-canvas";
import { ServiceToolDemo } from "./service-tool-demo";
import { ServicePricing } from "./service-pricing";
import { ServiceChapterBreak } from "./service-chapter-break";
import { hubScopes, serviceJourneys, specialistParents, serviceRelated, detailNotes } from "./service-experience-data";
import { RegionSection } from './region-section';
import { clientCases } from './portfolio-data';

const webdesignCase = clientCases.find(project => project.slug === 'beurswijzer')!;

function Breadcrumb({service,detail=false}:{service:Service;detail?:boolean}) {
  const parent=detail?specialistParents[service.slug]:null;
  return <nav className="experience-breadcrumb" aria-label="Broodkruimel"><a href="/diensten">Diensten</a><span aria-hidden="true">/</span>{parent&&<><a href={`/diensten/${parent[1]}`}>{parent[0]}</a><span aria-hidden="true">/</span></>}<span aria-current="page">{service.name}</span></nav>;
}
function Journey({service}:{service:Service}) {
  return <section className="wrap experience-journey" id="samenwerking"><div className="experience-section-head"><div><Eyebrow>Zo werken we samen</Eyebrow><h2>Van jouw vraag.<br/><em>Naar dagelijks gebruik.</em></h2></div><p>Je hoeft geen uitgewerkt plan klaar te hebben. We maken stap voor stap duidelijk wat nodig is, wie wat verzorgt en wat je ontvangt.</p></div><ol>{serviceJourneys[service.slug].map((text,i)=><li key={text} data-reveal><span>0{i+1}</span><h3>{["Jij brengt je vraag.","We werken het uit.","Je kunt ermee verder."][i]}</h3><p>{text}</p></li>)}</ol></section>;
}
function Questions({service}:{service:Service}) {
  // The editorial data chooses the questions; wording must never hide scope or cost terms.
  const questions=service.faqs;
  return <section className="wrap experience-questions"><FaqData path={`/diensten/${service.slug}`} questions={questions}/><Eyebrow>Voor je begint</Eyebrow><h2>Goed om te weten.</h2><div>{questions.map(([q,a])=><article key={q}><h3>{q}</h3><p>{a}</p></article>)}</div></section>;
}
function Closing({service}:{service:Service}) {
  return <section className="experience-closing"><div className="wrap"><div className="experience-closing-main"><div><Eyebrow>Jouw volgende stap / Sitesnit</Eyebrow><h2>Vertel waar je<br/><em>mee verder wilt.</em></h2></div><div><p>Een nieuw idee of iets dat nu niet lekker werkt: daar begint ons gesprek. Vanuit Baarlo werken we voor ondernemers in Venlo en Limburg. We denken mee over een passende aanpak en maken duidelijk wat je kunt laten verzorgen.</p><a className="button" href={service.contact}>{service.cta}<Arrow/></a></div></div><div className="experience-related"><span>Sluit hierop aan</span>{serviceRelated[service.slug].map(([title,text,slug])=><a href={`/diensten/${slug}`} key={slug}><div><b>{title}</b><span>{text}</span></div><Arrow/></a>)}</div></div></section>;
}

export function ServiceHub({service}:{service:Service}) {
  return <div className={`service-experience service-hub experience-${service.tone}`}>
    <header className="wrap experience-hub-hero"><Breadcrumb service={service}/><div className="hub-hero-grid"><div><Eyebrow>{service.name} / Venlo & Limburg</Eyebrow><h1>{service.title}<br/><em>{service.accent}</em></h1><p>{service.summary}</p><div className="service-hero-actions"><a className="button" href={service.contact}>{service.cta}<Arrow/></a><a className="text-link" href={service.slug==="webdesign"?"/diensten/webdesign/pakketten":"#mogelijkheden"}>{service.slug==="webdesign"?"Vergelijk de websitepakketten":"Bekijk de mogelijkheden"}<Arrow/></a></div></div><ServiceCanvas kind={service.slug}/></div></header>
    <section className="wrap experience-scopes" id="mogelijkheden"><div className="experience-section-head"><div><Eyebrow>De mogelijkheden</Eyebrow><h2>{service.introTitle}<br/><em>{service.introAccent}</em></h2></div><p>{service.intro}</p></div><div className="hub-scope-list">{hubScopes[service.slug].map((scope,i)=><article key={scope.id} id={scope.id} data-reveal><span className="scope-number">0{i+1}</span><div><h3>{scope.title}</h3><p>{scope.text}</p></div><div><ul>{scope.includes.map(item=><li key={item}>{item}</li>)}</ul><a className="text-link" href={scope.href}>{scope.link}<Arrow/></a></div></article>)}</div>{service.slug==="ai-automatisering"&&<p className="experience-small-note" id="rekentools">Een budgetplanner kan ingevoerde kosten en zelf aangeleverde offertes vergelijken. Automatisch actuele aanbieders vergelijken vraagt daarnaast om toegestane, actuele gegevensbronnen. We bespreken eerst welke gegevens beschikbaar zijn.</p>}</section>
    {service.slug==='webdesign'&&<section className="wrap experience-copy-note"><Eyebrow>Een ontwerpkeuze uit mijn werk</Eyebrow><h2>Uitleg en berekeningen.<br/><em>Elk een eigen plek.</em></h2><p>Bij Beurswijzer maakt de indeling verschil tussen rustig lezen en zelf een berekening verkennen. De interactieve onderdelen staan bij de uitleg waarvoor ze bedoeld zijn. De case laat de uitgewerkte schermen en functies zien; het is geen claim over extra aanvragen.</p><figure style={{maxWidth:900,margin:'28px 0'}}><div className="pair-device"><img src={webdesignCase.image} srcSet={`${webdesignCase.image} ${webdesignCase.imageSmallWidth}w, ${webdesignCase.imageLarge} ${webdesignCase.imageWidth}w`} sizes="(max-width: 1000px) 90vw, 900px" width={webdesignCase.imageWidth} height={webdesignCase.imageHeight} alt="Beurswijzer-homepage met twee vervolgroutes: inzichten ontdekken en de eigen maandruimte bekijken" loading="lazy" decoding="async"/></div><figcaption style={{marginTop:12}}>Twee routes naast elkaar: eerst inzichten lezen of direct je eigen maandruimte bekijken.</figcaption></figure><a className="text-link" href="/projecten/beurswijzer">Bekijk de keuzes in de Beurswijzer-case<Arrow/></a></section>}<ServiceToolRoute slug={service.slug}/><Journey service={service}/><ServicePricing slug={service.slug}/><Questions service={service}/><Closing service={service}/>
    {service.slug === 'webdesign' && <RegionSection/>}
  </div>;
}

export function ServiceDetail({service}:{service:Service}) {
  const monthly=["onderhoud-hosting","content","social-media"].includes(service.slug);
  return <div className={`service-experience experience-detail-page detail-${service.slug} experience-${service.tone}`}>
    <header className="wrap experience-detail-hero"><Breadcrumb service={service} detail/><Eyebrow>{service.name} / De verdieping</Eyebrow><div><h1>{service.title}<br/><em>{service.accent}</em></h1><div><p>{service.summary}</p><div className="service-hero-actions"><a className="button" href={service.contact}>{service.cta}<Arrow/></a><a className="text-link" href={service.slug==="seo-optimalisatie"?"/tools/seo-audit":monthly?"#maandpakketten":"#aanpak"}>{service.slug==="seo-optimalisatie"?"Doe eerst de gratis SEO-audit":monthly?"Bekijk pakketten & wat erbij hoort":"Van idee naar uitvoering"}<Arrow/></a></div></div></div><ul className="experience-tags">{service.tags.map(tag=><li key={tag}>{tag}</li>)}</ul></header>
    {monthly&&<ServicePricing slug={service.slug}/>}
    <section className="wrap experience-depth" id="aanpak"><div className="experience-depth-intro"><div><Eyebrow>Wat erachter zit</Eyebrow><h2>{service.introTitle}<br/><em>{service.introAccent}</em></h2><p>{service.intro}</p></div><ServiceCanvas kind={service.slug} animated/></div><div className="experience-chapters">{service.methods.flatMap(([title,text],i)=>[...(i===2?[service.slug==="formulieren-rekentools"?<div className="chapter-demo-break" key="interactive-demo"><ServiceToolDemo/></div>:<ServiceChapterBreak key="visual-break" kind={service.slug}/>]:[]),<article key={title} id={service.slug==="ai-koppelingen"?(i===1?"taal-documenten":i===2?"software":undefined):undefined} data-reveal><div className="chapter-index"><span>0{i+1}</span><i aria-hidden="true"/></div><div><h3>{title}</h3><p>{text}</p>{detailNotes[service.slug]?.[i]&&<p>{detailNotes[service.slug][i]}</p>}</div></article>])}</div></section>
    {service.slug==="formulieren-rekentools"&&<section className="wrap experience-demo-section"><aside className="experience-case-note"><span>Een voorbeeld uit ons werk</span><p>Voor Beurswatcher maakten we interactieve berekeningen waarin inleg, looptijd en rendement een grafiek worden. De cijfers volgen vaste rekenregels.</p><a className="text-link" href="/projecten/beurswatcher">Bekijk de rekentool in de case<Arrow/></a></aside></section>}
    {service.slug==="seo-optimalisatie"&&<section className="wrap experience-copy-note"><Eyebrow>Demonstratie / Geen werkelijk klantresultaat</Eyebrow><h2>Van een kapotte verwijzing.<br/><em>Naar gecontroleerd herstel.</em></h2><p>Een link op een dienstenpagina opent een verdwenen adres. Ik onderzoek eerst welke pagina de bedoelde uitleg nu geeft. Is er een passende bestaande bestemming, dan pas ik de bronlink aan. Daarna controleer ik de bron, de bestemming en de route naar contact opnieuw. Zonder passende opvolger is doorsturen naar de homepage geen automatische oplossing.</p><p>Voor echt herstel leg ik de betrokken pagina’s, toegang en werkzaamheden vooraf vast. Na uitvoering krijg je uitleg over wat is aangepast, wat is gecontroleerd en wat nog openstaat. De gratis audit geeft aanwijzingen; de betaalde opdracht omvat alleen het afgesproken onderzoek en uitvoerwerk.</p><a className="text-link" href="/404-fouten-oplossen">Lees wanneer een 404 wél moet worden hersteld<Arrow/></a></section>}
    {service.slug==="content"&&<section className="wrap experience-copy-note"><Eyebrow>Ook als eenmalige opdracht</Eyebrow><h2>De juiste woorden.<br/><em>Op je belangrijkste pagina’s.</em></h2><p>Nieuwe webteksten, een dienstenpagina die duidelijker moet of producten die betere uitleg verdienen: copywriting kan ook zonder blogabonnement. We bepalen de benodigde pagina’s, beschikbare informatie en gewenste toon. Je ontvangt vooraf een voorstel voor die opdracht.</p><h3>Fictief tekstvoorbeeld — geen gemeten klantresultaat</h3><p><b>Voor:</b> “Wij bieden professionele oplossingen met kwaliteit.” <b>Na:</b> “Een boekenkast voor een schuine wand? We meten de ruimte op en bespreken indeling, materiaal en afwerking. Daarna ontvang je een voorstel voor de kast.”</p><p>De tweede tekst noemt de dienst, doelgroep en volgende stap. Die informatie gebruiken we alleen als het bedrijf deze werkwijze bevestigt. Nieuwe artikelen vallen onder het gekozen blogpakket; aanpassingen aan bestaande pagina’s kunnen binnen een afgesproken onderhoudsopdracht horen. We controleren eerst welke dekking je al hebt.</p><a className="text-link" href="/contact?dienst=content">Bespreek je webteksten<Arrow/></a></section>}
    <ServiceToolRoute slug={service.slug}/><Journey service={service}/>{!monthly&&<ServicePricing slug={service.slug}/>}<Questions service={service}/><Closing service={service}/>
  </div>;
}
