import { AppCanvas } from './app-canvas';
import { WebappCanvas } from './webapp-canvas';
import { Arrow } from "./ui";

export function ServiceChapterBreak({kind}:{kind:string}) {
  const brand=kind==="branding",content=kind==="content",social=kind==="social-media",care=kind==="onderhoud-hosting",seo=kind==="seo-optimalisatie",shop=kind==="webshops";
  return <figure className={`chapter-break break-${kind}`} data-scroll-scene="unfold"><div className="break-layout">
    {kind === "apps" ? <><div className="break-copy"><span>Voorbeeld / Een taak op je telefoon</span><strong>Even openen.<br/><em>En verder kunnen.</em></strong><p>Een afspraak bekijken, een aanvraag doorgeven en de voortgang terugvinden. De schermen volgen de handeling die iemand wil afronden.</p></div><AppCanvas /></> : kind === "webapps" ? <><div className="break-copy"><span>Voorbeeld / Samenwerken met passende toegang</span><strong>Een eigen dossier.<br/><em>Een duidelijke volgende stap.</em></strong><p>Klanten leveren informatie aan en zien hun eigen voortgang. Een medewerker controleert wat binnenkomt. De toegangsrechten bepalen wie wat mag bekijken en wijzigen.</p></div><WebappCanvas /></> : brand?<>
      <div className="break-copy"><span>Je identiteit in gebruik</span><strong>Hetzelfde karakter.<br/><em>Een andere vorm.</em></strong><p>Een website, socialbericht of offerte krijgt zijn eigen indeling. Logo, kleuren en typografie houden het geheel herkenbaar.</p></div>
      <div className="brand-applications" data-scene-target aria-label="Schematische toepassingen van één huisstijl"><div className="brand-web"><div><i/>jouw merk<span>↗</span></div><b>Een eigen<br/>verhaal.</b><span>Op je website</span></div><div className="brand-post"><i/><b>Goed werk.<br/>Mooi verteld.</b><span>Op je kanalen</span></div><div className="brand-document"><span>JOUW MERK</span><b>Een helder voorstel.</b><i/><i/><i/><span>In je documenten</span></div></div>
    </>:content?<>
      <div className="break-copy"><span>De opbouw van een artikel</span><strong>Een lezer zoekt<br/><em>een antwoord.</em></strong><p>Elke laag doet iets anders. Een herkenbare vraag trekt aandacht, jouw uitleg helpt verder en een relevante link verbindt het verhaal met je aanbod.</p></div>
      <div className="article-anatomy" data-scene-target><div><span>De vraag herkennen</span><b>Wat wil je klant<br/>eerst weten?</b></div><div><span>Vanuit je expertise uitleggen</span><p>Een concreet antwoord, praktische stappen en een voorbeeld uit jouw werk.</p><i/><i/></div><div><span>Een passende vervolgstap</span><b>Van artikel naar je dienst<Arrow/></b></div></div>
    </>:social?<>
      <div className="break-copy"><span>Voorbeeld / Vier basisposts</span><strong>Variatie in je inhoud.<br/><em>Herkenning in je stijl.</em></strong><p>Je hoeft niet iedere keer hetzelfde te vertellen. Vanuit verschillende onderwerpen maken we passende berichten voor je gekozen kanalen.</p></div>
      <div className="post-mix" data-scene-target>{[["01","Je werk","Een project laten zien."],["02","Een klantvraag","Iets begrijpelijk uitleggen."],["03","Jouw kennis","Een praktisch advies delen."],["04","Een artikel","Een onderwerp verdiepen."]].map(([n,title,text])=><div key={n}><span>POST {n}</span><b>{title}</b><p>{text}</p><i aria-hidden="true"/></div>)}</div>
    </>:care?<>
      <div className="break-copy"><span>Voorbeelden / Technisch onderhoud</span><strong>Een controle.<br/><em>Een concreet vervolg.</em></strong><p>Bij een technische fout kijken we wat er misgaat en herstellen we de bestaande werking. Dit soort taken hoort bij de onderhoudspakketten.</p></div>
      <div className="maintenance-comparison" data-scene-target><div className="comparison-heading"><span>Wat de controle laat zien</span><span>Wat we aanpakken</span></div>{[["Een link loopt dood","De verwijzing herstellen"],["Een formulier geeft een fout","De bestaande invoerroute herstellen"],["Een pagina laadt langzaam","Oorzaak onderzoeken en techniek aanpassen"]].map(([before,after])=><div className="comparison-row" key={before}><span>{before}</span><Arrow/><b>{after}</b></div>)}</div>
    </>:seo?<>
      <div className="break-copy"><span>Inhoud die samenhangt</span><strong>Eén onderwerp.<br/><em>Logisch verbonden.</em></strong><p>Je dienstenpagina geeft het overzicht. Aanvullende uitleg beantwoordt echte vervolgvragen en verwijst terug naar de passende dienst. Verwante vragen houden we bij elkaar.</p></div>
      <div className="seo-page-tree" data-scene-target><div className="tree-root"><span>HET VERTREKPUNT</span><b>Je dienst</b><p>Wat je doet, voor wie en hoe het werkt.</p></div><div className="tree-branches"><div><span>VERDIEPING</span><b>Een klantvraag</b><p>Een praktisch, volledig antwoord.</p></div><div><span>CONTEXT</span><b>Uitleg uit je vak</b><p>Een voorbeeld dat iets verduidelijkt.</p></div></div><span className="tree-return">Relevante links verbinden de pagina’s ↗</span></div>
    </>:<>
      <div className="break-copy"><span>{shop?"De route achter een bestelling":"Voorbeeld / Een aanvraag verwerken"}</span><strong>{shop?"Je klant bestelt.":"Informatie komt binnen."}<br/><em>{shop?"Jij kunt verder.":"Het werk gaat verder."}</em></strong><p>{shop?"De gegevens van de klant verbinden de voorkant van je winkel met jouw verwerking. We spreken af welk systeem iedere stap beheert.":"Een koppeling geeft de aanvraag een plek. AI kan een concept voorbereiden. Waar nodig controleert een medewerker voordat er iets wordt verstuurd."}</p></div>
      <div className="handover-illustration" data-scene-target>{(shop?[["01 / KLANT","De bestelling","Product · variant · adres"],["02 / WINKEL","De bevestiging","Betaalstatus · bezorgkeuze"],["03 / BEDRIJF","De verwerking","Order · voorraad · administratie"]]:[["01 / BINNENKOMST","De aanvraag","Vraag · contact · bijlage"],["02 / VERWERKING","Het klantdossier","Gegevens controleren & koppelen"],["03 / CONTROLE","Een concept klaar","Medewerker beoordeelt & verstuurt"]]).map(([n,title,text],i)=><div key={n}><span>{n}</span><b>{title}</b><p>{text}</p>{i<2&&<Arrow/>}</div>)}</div>
    </>}
  </div></figure>;
}
