export const hubSlugs = ["webdesign", "seo", "ai-automatisering"];
type Scope = {id:string;title:string;text:string;includes:string[];href:string;link:string};
export const hubScopes:Record<string,Scope[]> = {
  webdesign:[
    {id:"apps",title:"Een eigen app op de telefoon.",text:"Maak terugkerende handelingen bereikbaar via een app voor iPhone of Android. We ontwerpen, bouwen en bereiden de appwinkelpublicatie voor.",includes:["Een mobiele route rond de belangrijkste taak","De afgesproken telefoonfuncties en koppelingen","Testen en voorbereiding voor App Store of Google Play"],href:"/diensten/apps",link:"Apps voor iPhone & Android"},
    {id:"webapps",title:"Een omgeving om in te werken.",text:"Laat klanten documenten aanleveren of medewerkers aanvragen behandelen. Een webapp brengt informatie, rollen en taken bij elkaar, ook op mobiel.",includes:["Inloggen en passende toegang per gebruiker","Klantportalen, dashboards en interne processen","Een eerste versie rond de belangrijkste taak"],href:"/diensten/webapps",link:"Webapps, inloggen & klantportalen"},
    {id:"websites",title:"Websites die je verhaal dragen.",text:"Een onepager houdt een compact aanbod bij elkaar. Een bedrijfswebsite geeft diensten, werk en je bedrijf ieder een eigen plek. Bij maatwerk volgen pagina’s en functies uit wat je bezoeker moet kunnen doen.",includes:["Een heldere indeling en contactroute","Ontwerp vanaf mobiel, passend bij je bedrijf","Afgesproken inhoud, functies en technische controles"],href:"/diensten/webdesign/pakketten",link:"Onepager, vijf pagina’s & maatwerk uitgelegd"},
    {id:"webshops",title:"Een winkel die verder denkt.",text:"Van productkeuze tot orderverwerking: een webshop moet aan beide kanten prettig werken. We bepalen categorieën, varianten, betaal- en bezorgmogelijkheden en de gegevens die je nodig hebt om een bestelling af te handelen.",includes:["Assortiment, productpagina’s en mobiel afrekenen","Voorraad- en betaalwerking op basis van je systemen","Afzonderlijk voorstel voor de volledige winkel"],href:"/diensten/webshops",link:"De opbouw en werking van een webshop"},
    {id:"merk",title:"Een herkenbaar merk eromheen.",text:"Een logo, kleurenpalet, typografie en een eigen toon geven richting aan je website. We kunnen een nieuwe identiteit ontwikkelen of versterken wat je al hebt. Bedrijfsfotografie en video verzorgen we via een externe partner.",includes:["Logo, kleuren en praktische merktoepassingen","Teksten die je aanbod begrijpelijk maken","Eigen foto’s en video als afzonderlijke opdracht"],href:"/diensten/branding",link:"Van merkrichting naar huisstijl & beeld"}
  ],
  seo:[
    {id:"optimalisatie",title:"Een antwoord op echte zoekvragen.",text:"We verbinden wat jouw klanten zoeken met relevante pagina’s. Duidelijke titels, inhoud en interne links geven onderwerpen een eigen plek. Tegelijk bekijken we bereikbaarheid, mobiele bruikbaarheid en de technische basis van je website.",includes:["Zoekintentie, paginastructuur en bestaande teksten","Technische SEO en relevante interne links","Lokale inhoud vanuit je echte werkgebied"],href:"/diensten/seo-optimalisatie",link:"Zo pakken we SEO-optimalisatie aan"},
    {id:"content",title:"Jouw vakkennis, helder uitgewerkt.",text:"We schrijven webteksten en artikelen op basis van je diensten, expertise en klantvragen. Met een blogpakket verschijnen twee of vier nieuwe artikelen per maand. Onderzoek, schrijven, SEO-opmaak en publiceren zijn inbegrepen.",includes:["Eenmalige webcopy of een vast blogritme","Onderwerpen die iets toevoegen aan je website","Inhoudelijke controle vooraf afgestemd"],href:"/diensten/content",link:"Copywriting, blogaanpak & maandpakketten"},
    {id:"social-media",title:"Hetzelfde verhaal. Passend per kanaal.",text:"Een project, klantvraag of blog krijgt een passende vorm op Instagram, Facebook en LinkedIn. We maken de basisposts geschikt voor jouw gekozen platforms, plannen de inhoud en plaatsen de afgesproken berichten.",includes:["Vier, zes of acht posts per platform per maand","Eén, twee of drie platforms naar keuze","Reacties, privéberichten en advertenties apart"],href:"/diensten/social-media",link:"Socialmedia-aanpak & alle combinaties"}
  ],
  "ai-automatisering":[
    {id:"formulieren",title:"Van invullen naar iets bruikbaars.",text:"Een contactaanvraag, intake of offerteformulier vraagt de juiste gegevens in een logische volgorde. Een rekentool vertaalt invoer naar een begrijpelijke uitkomst. We leggen ook vast waar aanvragen terechtkomen en hoe opvolging werkt.",includes:["Duidelijke vragen, invoercontrole en foutmeldingen","Vaste, testbare berekeningen en zichtbare aannames","Bevestiging, opslag of een afgesproken overdracht"],href:"/diensten/formulieren-rekentools",link:"Formulieren, rekentools & een werkende demo"},
    {id:"ai-assistenten",title:"Taal en documenten laten voorbereiden.",text:"AI kan bedrijfsinformatie doorzoekbaar maken, gegevens uit documenten ordenen of een antwoord als concept voorbereiden. We kiezen de bronnen en bepalen wanneer een medewerker controleert of overneemt.",includes:["Assistenten op basis van je eigen bedrijfskennis","Documentverwerking met afgesproken controles","Een afgebakende taak en duidelijke overdracht"],href:"/diensten/ai-koppelingen#taal-documenten",link:"AI-toepassingen en de controle eromheen"},
    {id:"koppelingen",title:"Software die werk aan elkaar doorgeeft.",text:"Een aanvraag kan een klantdossier worden; een bestelling kan naar je administratie. We onderzoeken beschikbare API’s en rechten, brengen velden bij elkaar en bouwen controles voor ontbrekende of dubbele gegevens.",includes:["Backend, API’s en bestaande software verbinden","Verwerkingsregels, foutmeldingen en uitzonderingen","Testen op het proces waarin jij dagelijks werkt"],href:"/diensten/ai-koppelingen#software",link:"Van systemen naar een werkende koppeling"}
  ]
};

export const serviceJourneys:Record<string,[string,string,string]> = {
  apps:["Je vertelt wie de app gaat gebruiken, welke taak centraal staat en of je iPhone, Android of beide wilt bereiken.","We ontwerpen de belangrijkste schermen en bouwen de afgesproken werking. We testen de gebruikersroutes en bereiden de appwinkelpublicatie met je voor.","We begeleiden de afgesproken publicatiestappen. Toegang, beheer en toekomstige updates leggen we vast; de appwinkels beoordelen de inzending."],
  webapps:["Je vertelt welke taak eenvoudiger moet, wie de toepassing gebruikt en welke informatie er al is.","We werken schermen, rollen, gegevens en uitzonderingen uit. We bouwen en testen eerst de afgesproken belangrijkste route.","Je ontvangt de werkende webapp en uitleg over het gebruik. Toegang, beheer, back-ups en eventuele uitbreiding leggen we vast."],
  webdesign:["Je vertelt over je bedrijf, bezoekers en aanbod. We bekijken bestaande teksten, beelden en huisstijl en bepalen wie wat aanlevert.","We werken de pagina’s en contactroute uit, ontwerpen vanaf mobiel en bouwen de afgesproken inhoud en functies. Je beoordeelt het ontwerp en de uitwerking.","Je website wordt opgeleverd met de afgesproken pagina’s en een gecontroleerde contactroute. Hosting, toegang en verder onderhoud leggen we vast."],
  webshops:["Je deelt je assortiment, varianten, prijzen en productinformatie. We bespreken voorraad, bezorging, betaalmogelijkheden en de software die je gebruikt.","We ontwerpen productpagina’s en de bestelroute. Daarna bouwen en testen we de afgesproken betaal-, bezorg- en verwerkingsstromen.","Klanten kunnen via de afgesproken route bestellen. Jij weet waar orders terechtkomen en hoe de winkel wordt beheerd. Productcontent en onderhoud kun je erbij afspreken."],
  branding:["Je laat zien hoe je bedrijf zich nu presenteert en welke indruk je wilt maken. We kiezen welke herkenbare onderdelen behouden blijven.","We werken de merkrichting uit in logo, kleuren en typografie, en laten zien hoe die op je website en andere uitingen samenkomen.","Je ontvangt de afgesproken bestanden en praktische uitleg voor het gebruik. Fotografie, video of toepassing in een nieuwe website kunnen aansluiten."],
  seo:["Je deelt je aanbod, klantvragen en werkgebied. Bestaande zoekgegevens en goede inhoud nemen we mee waar beschikbaar.","We bepalen welke pagina’s en onderwerpen aandacht verdienen. Daarop stemmen we inhoud, techniek en een eventueel publicatieritme af.","Je krijgt de afgesproken verbeteringen of publicaties. Beschikbare gegevens helpen bepalen welke inhoud daarna aandacht vraagt."],
  content:["Je deelt expertise, veelgestelde vragen en ontwikkelingen in je bedrijf. We spreken de toon, inhoudelijke controle en beschikbare beelden af.","We onderzoeken onderwerpen, schrijven, verzorgen de SEO-opmaak en publiceren de gekozen hoeveelheid blogs. Eenmalige webcopy plannen we als eigen opdracht.","Je website krijgt de afgesproken nieuwe inhoud. Publicaties verdelen we over de maand en verbinden we met relevante diensten of artikelen."],
  "social-media":["Je kiest Instagram, Facebook en/of LinkedIn en het aantal posts per maand. Je deelt nieuws, beschikbare beelden en toegang tot de gekozen kanalen.","We maken basisposts, passen tekst en vorm per platform aan en stemmen de planning en controle af. Daarna plaatsen we de afgesproken berichten.","Je kanalen krijgen een herkenbaar ritme. Nieuwe ontwikkelingen geef je door; reacties, privéberichten en advertenties vallen onder een aparte afspraak."],
  "onderhoud-hosting":["Je deelt je huidige website en beschikbare toegang. We bekijken de techniek en of er eerst werk nodig is voordat we het beheer overnemen.","Samen kiezen we hosting, technisch onderhoud of onderhoud met SEO. We leggen vast wat wordt beheerd, hoe je wijzigingen doorgeeft en welke externe diensten meedoen.","De gekozen werkzaamheden worden verzorgd. Met technisch onderhoud controleren we maandelijks snelheid en fouten; met SEO werken we ook aan bestaande teksten en code."],
  "ai-automatisering":["Je kiest één terugkerende taak en laat zien welke informatie binnenkomt, wie ermee werkt en welke systemen meedoen.","We bepalen welke stappen te vereenvoudigen zijn, werken de oplossing uit en testen invoer, verwerking, uitzonderingen en overdracht.","Je gebruikt de afgesproken tool of gegevensstroom met duidelijke controlepunten. Eventueel softwaregebruik en onderhoud worden vooraf inzichtelijk gemaakt."],
  "seo-optimalisatie":["Je deelt je aanbod, werkgebied, klantvragen en beschikbare toegang tot je website en zoekgegevens.","We bepalen prioriteiten en voeren de afgesproken inhoudelijke en technische verbeteringen uit. Jouw vakkennis gebruiken we om teksten te controleren.","Je hebt aangepaste pagina’s en een duidelijk vertrekpunt voor verdere verbetering. Nieuwe content en doorlopend onderhoud kun je afzonderlijk kiezen."],
  "formulieren-rekentools":["Je vertelt welke aanvraag of berekening nodig is en wie de uitkomst gebruikt. Je deelt voorbeelden en de regels waaraan invoer moet voldoen.","We ontwerpen de vragen, bouwen de werking en testen afgesproken scenario’s. Bij een calculator controleren we ook berekeningen, eenheden en afronding.","Bezoekers kunnen gegevens invullen en ontvangen de afgesproken bevestiging of uitkomst. Jij weet waar aanvragen terechtkomen en hoe je ermee verder werkt."],
  "ai-koppelingen":["Je kiest een terugkerende taak en laat zien welke systemen, gegevens en mensen meedoen. We onderzoeken de beschikbare toegangs- en koppelmogelijkheden.","We werken de stappen uit, bouwen de afgesproken oplossing en testen verwerking en uitzonderingen. Je beoordeelt of de uitkomst in je werk bruikbaar is.","Je gebruikt de oplossing met duidelijke controlepunten. We leggen vast hoe je toegang beheert en welke softwarekosten of onderhoudswerkzaamheden erbij horen."]
};

export const specialistParents:Record<string,[string,string]> = {
  webapps:["Webdesign & webshops","webdesign"],
  webshops:["Webdesign & webshops","webdesign"],branding:["Webdesign & webshops","webdesign"],
  content:["SEO, content & social media","seo"],"social-media":["SEO, content & social media","seo"],"seo-optimalisatie":["SEO, content & social media","seo"],
  "formulieren-rekentools":["Tools & automatisering","ai-automatisering"],"ai-koppelingen":["Tools & automatisering","ai-automatisering"]
};

export const serviceRelated:Record<string,[string,string,string][]> = {
  apps:[["Webapps & klantportalen","Een omgeving in de browser, naast of in plaats van je app.","webapps"],["Webdesign","Een website waarop mensen je app ontdekken.","webdesign"],["Softwarekoppelingen","Je app verbinden met je bestaande gegevens.","ai-koppelingen"]],
  webapps:[["Apps voor iPhone & Android","Een eigen app via de App Store of Google Play.","apps"],["Webdesign","Een openbare website naast je klantomgeving.","webdesign"],["AI & koppelingen","Je bestaande software laten samenwerken.","ai-koppelingen"],["Hosting & onderhoud","Beheer en aandacht na oplevering.","onderhoud-hosting"]],
  webdesign:[["Merk & identiteit","Een herkenbaar gezicht op ieder kanaal.","branding"],["Formulieren & rekentools","Meer laten doen met je website.","formulieren-rekentools"],["Hosting & onderhoud","De aandacht na je lancering.","onderhoud-hosting"]],
  seo:[["SEO-optimalisatie","Inhoud en techniek gericht verbeteren.","seo-optimalisatie"],["Hosting & onderhoud","Bestaande teksten en code bijhouden.","onderhoud-hosting"]],
  "ai-automatisering":[["Formulieren & rekentools","De vragen en berekeningen aan de voorkant.","formulieren-rekentools"],["AI & koppelingen","De verwerking achter de schermen.","ai-koppelingen"]],
  webshops:[["Merk & identiteit","Een winkel die bij je bedrijf past.","branding"],["AI & koppelingen","Orders verder verwerken in je software.","ai-koppelingen"],["Content & copywriting","Producten begrijpelijk beschrijven.","content"]],
  branding:[["Webdesign & webshops","Je merk toepassen in een eigen website.","webdesign"],["Social media","Herkenbaar blijven op je kanalen.","social-media"]],
  content:[["SEO-optimalisatie","Nieuwe artikelen verbinden met sterke pagina’s.","seo-optimalisatie"],["Social media","Je onderwerpen passend hergebruiken.","social-media"]],
  "social-media":[["Content & blogs","Een onderwerp op je website verdiepen.","content"],["Merk & identiteit","Een duidelijke basis voor tekst en beeld.","branding"]],
  "onderhoud-hosting":[["Content & blogs","Twee of vier nieuwe artikelen per maand.","content"],["Social media","Je verhaal ook op je kanalen bijhouden.","social-media"],["SEO-optimalisatie","Een grotere inhoudelijke of technische stap.","seo-optimalisatie"]],
  "seo-optimalisatie":[["Content & blogs","Nieuwe vragen inhoudelijk beantwoorden.","content"],["Hosting & onderhoud","De bestaande basis blijven verbeteren.","onderhoud-hosting"]],
  "formulieren-rekentools":[["AI & koppelingen","Aanvragen aan je bestaande software koppelen.","ai-koppelingen"],["Webdesign & webshops","Je tool onderdeel maken van een sterke website.","webdesign"]],
  "ai-koppelingen":[["Formulieren & rekentools","Goede invoer als start van je proces.","formulieren-rekentools"],["Webshops","Je bestel- en verwerkingsroute verbinden.","webshops"]]
};

export const detailNotes:Record<string,[string|null,string|null,string|null,string|null]> = {
  webshops:["Jij levert de beschikbare productgegevens en beelden aan. Samen bepalen we of er eerst teksten, categorieën of ontbrekende gegevens moeten worden uitgewerkt.","De bezoeker moet vooraf begrijpen wat hij bestelt en welke keuzes nog nodig zijn. Ook een mislukte betaling of onvolledig adres krijgt een duidelijke vervolgstap.","We leggen vast welk systeem de voorraad en orderstatus beheert. Zo is duidelijk waar je gegevens wijzigt en welke informatie wordt doorgegeven.","We spreken af hoe je orders en producten beheert. Softwareabonnementen en eventuele betaaltransactiekosten worden als afzonderlijke kosten besproken."],
  branding:[null,"Je ziet de gekozen stijl in toepassingen, zodat je kunt beoordelen hoe kleuren en letters op een scherm of in een bericht samenkomen.",null,null],
  content:[null,"Voor vakinhoud gebruiken we jouw input en controle. Ook eenmalige dienstenpagina’s, productteksten en een complete herschrijving kunnen worden uitgewerkt.",null,"De publicaties verdelen we over de maand. We spreken af wanneer input en feedback nodig zijn, zodat inhoudelijke controle onderdeel is van de planning."],
  "social-media":["Je kiest één, twee of drie platforms. LinkedIn kan ruimte geven aan zakelijke uitleg; op Instagram of Facebook passen we tekst en presentatie aan de gekozen inhoud aan.",null,"Je weet welke inhoud wordt voorbereid en wanneer jouw controle nodig is. De afgesproken toegang maakt het mogelijk om het plaatsen uit handen te geven.",null],
  "onderhoud-hosting":["Heb je al een website, dan bekijken we eerst de huidige opbouw en toegang. Een verhuizing of herstel van achterstallige problemen kan vooraf extra werk vragen; dat stemmen we apart af.","De maandelijkse controle hoort bij technisch onderhoud. Alleen hosting omvat het online houden van de website en neemt deze controles of wijzigingen niet over.",null,"Je kunt klein beginnen en later bespreken of meer beheer past. We houden het verschil tussen terugkerend onderhoud en een nieuwe ontwikkelopdracht duidelijk."]
};
