import { Arrow, Eyebrow } from "./ui";
import { CareOffers, type CareCategory } from "./care-offers";
export function ServiceContext({slug}:{slug:string}) {
  if (slug === "webdesign") return <section className="wrap service-deep-links"><div><Eyebrow>Het hele merk</Eyebrow><h2>Logo, kleur, beeld.<br /><em>Een kloppend geheel.</em></h2><p>Van een complete huisstijl tot eigen foto’s en video via een externe partner. We stemmen de onderdelen af die jouw website nodig heeft.</p><a className="text-link" href="/diensten/branding">Meer over merk & identiteit <Arrow /></a></div><div><Eyebrow>Online verkopen</Eyebrow><h2>Ook voor<br /><em>je webshop.</em></h2><p>Producten, varianten, betalen en orderverwerking vragen om een eigen ontwerp en technische uitwerking.</p><a className="text-link" href="/diensten/webshops">Ontdek webshops <Arrow /></a></div></section>;
  if (slug === "ai-automatisering") return <section className="wrap automation-blueprint" id="formulieren"><div><Eyebrow>Voorbeeld / Van aanvraag naar opvolging</Eyebrow><h2>Een aanvraag komt binnen.<br /><em>Het voorbereidende werk staat klaar.</em></h2><p>Een proces dat je per stap kunt begrijpen en controleren. De koppelingen worden afgestemd op de software en toegangsrechten van je bedrijf.</p></div><ol>{[
    ["Invoer","Een formulier of klantmail met de vraag, contactgegevens en bijlagen."],
    ["Verwerking","AI kan de vraag samenvatten. Vaste regels controleren velden en een koppeling zoekt het passende klantdossier."],
    ["Controle","Ontbrekende informatie, dubbele contacten en een conceptantwoord komen op een duidelijke controlelijst."],
    ["Vervolg","Een medewerker keurt de reactie goed. Het dossier en de taak staan op de juiste plek, zonder opnieuw overtypen."]
  ].map(([title,text],i)=><li key={title} data-reveal><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol><div className="automation-note" id="koppelingen"><h3>Complexe backend, duidelijke afspraken.</h3><p>We bepalen welke gegevens leidend zijn, wie toegang heeft en hoe wijzigingen tussen systemen doorstromen. We bouwen controles tegen dubbele verwerking en leggen mislukte stappen herkenbaar vast, zodat ze gericht opnieuw kunnen worden uitgevoerd. Dat vraagt meer dan alleen een koppeling aanzetten.</p></div></section>;
  if (slug === "seo") return <section className="wrap regional-note"><Eyebrow>Lokale verdieping</Eyebrow><h2>Venlo en omstreken.<br /><em>Relevantie begint bij je bedrijf.</em></h2><p>Voor een regionale dienstverlener zijn het werkgebied, bereikbaarheid en concrete werkzaamheden belangrijk. Voor een webshop kan landelijk productaanbod juist het vertrekpunt zijn. We stemmen pagina’s af op die verschillen en verbinden diensten met eigen werk en relevante vragen uit de regio.</p><p>Je bedrijfsgegevens, een eventueel Google Bedrijfsprofiel en bestaande reviews nemen we mee waar ze beschikbaar zijn. Klanten zien zo waar je werkt, wat je doet en hoe anderen de samenwerking ervaren.</p><a className="text-link" href="/diensten/onderhoud-hosting">Doorlopende SEO & onderhoud <Arrow /></a></section>;
  if (["content","social-media","onderhoud-hosting"].includes(slug)) return <><CareOffers category={slug as CareCategory} />{slug === "onderhoud-hosting" && <div className="wrap care-related-note"><p>Het SEO-pakket verbetert bestaande teksten en code. Voor nieuwe artikelen kies je een apart blogpakket.</p><div><a className="text-link" href="/diensten/seo">Onze SEO-aanpak <Arrow /></a><a className="text-link" href="/diensten/content">Nieuwe blogs & copywriting <Arrow /></a></div></div>}</>;
  return null;
}

