import {Arrow,Eyebrow} from './ui';
const routes:Record<string,{title:string;body:string;href:string;action:string;guide:string;guideLabel:string}>= {
 webdesign:{title:'Maak je ideeën alvast zichtbaar.',body:'Kies je inhoud, stijl en kleuren. Je voorbeeld helpt ons begrijpen welke richting bij je bedrijf past; het is nog geen definitief ontwerp.',href:'/tools/website-ontwerp-tool',action:'Maak jouw websitevoorbeeld',guide:'/website-structuur',guideLabel:'Hoe verdeel je inhoud over je pagina’s?'},
 seo:{title:'Waar loopt jouw website vast?',body:'Start met een gratis technische steekproef van maximaal twintig pagina’s. Je krijgt gevonden problemen mét bewijs. Daarna bepalen we welk herstel of welke inhoudelijke verbetering zinvol is.',href:'/tools/seo-audit',action:'Onderzoek je website',guide:'/seo-audit-checklist',guideLabel:'Wat hoort bij een goede SEO-audit?'},
 'ai-automatisering':{title:'Welke taak kost je steeds opnieuw tijd?',body:'Beschrijf een terugkerend proces. Het automatiseringsplan brengt invoer, stappen en uitzonderingen bij elkaar, zodat we een concrete verbetering kunnen bespreken.',href:'/tools/automatiseringsplan',action:'Breng je proces in kaart',guide:'/bedrijfsprocessen-automatiseren',guideLabel:'Welk proces kun je het beste automatiseren?'},
 'onderhoud-hosting':{title:'Weet waarvoor je maandelijks betaalt.',body:'Hosting, onderhoud en nieuwe inhoud zijn verschillende werkzaamheden. Zet de afspraken en bekende kosten van voorstellen naast elkaar voordat je kiest.',href:'/tools/website-offerte-vergelijken',action:'Vergelijk afspraken en kosten',guide:'/website-onderhoud-kosten',guideLabel:'Welke werkzaamheden horen bij onderhoud?'},
 content:{title:'Begrijpt je bezoeker wat je aanbiedt?',body:'Onderzoek boodschap, vertrouwen en de route naar contact. De websitecheck helpt de ontbrekende uitleg concreet maken voordat je teksten laat herschrijven.',href:'/tools/website-check',action:'Beoordeel je website',guide:'/website-levert-geen-aanvragen-op',guideLabel:'Waarom levert een website geen aanvragen op?'},
 webshops:{title:'Maak de omvang van je webshop duidelijk.',body:'Pagina’s, producten en koppelingen bepalen wat er gebouwd moet worden. De prijscheck verzamelt je wensen en maakt duidelijk wat nog afgestemd moet worden.',href:'/tools/website-kosten-berekenen',action:'Verken je websiteplan',guide:'/website-offerte-aanvragen',guideLabel:'Wat zet je in een bruikbare websitebriefing?'},
};
export function ServiceToolRoute({slug}:{slug:string}) {const r=routes[slug];if(!r)return null;return <section className="wrap service-tool-discovery"><div><Eyebrow>Eerst zelf verkennen</Eyebrow><h2>{r.title}</h2><p>{r.body}</p><a className="button" href={r.href}>{r.action}<Arrow/></a></div><aside><span>Voor je begint</span><a href={r.guide}>{r.guideLabel}<Arrow/></a><p>Praktische uitleg bij deze keuze. Geen verplicht tussenstation.</p></aside></section>;}
