import type {AuditReport} from '../../../lib/seo-audit/crawl';
const explanations:Record<string,{title:string;why:string}>={
 http:{title:'Pagina bereikbaar',why:'HTTP 200 maakt de pagina technisch bereikbaar. Dit zegt niets over laadsnelheid.'},
 noindex:{title:'Indexeringsinstructies gecontroleerd',why:'Zonder noindex kan een zoekmachine de pagina in principe opnemen. Of Google dat werkelijk doet, controleren we hiermee niet.'},
 title:{title:'Paginatitel aanwezig',why:'De titel benoemt het onderwerp in het tabblad en kan in Google verschijnen. Tekstkwaliteit en zoekpositie zijn hiermee niet beoordeeld.'},
 'canonical-multiple':{title:'Canonical-verwijzingen gecontroleerd',why:'Deze controle zoekt meervoudige hoofdversies. Geen canonical is ook een geslaagde controle op meervoudige verwijzingen, maar geen bewijs dat de voorkeurs-URL juist is.'},
 alt:{title:'Alt-attributen gecontroleerd',why:'Tekstalternatieven helpen bij het begrijpen van afbeeldingen. Een aanwezige of bewust lege alt is nog geen inhoudelijke beoordeling.'},
 json:{title:'JSON-LD-syntaxis gecontroleerd',why:'Geldige JSON kan technisch worden uitgelezen. Verplichte eigenschappen en geschiktheid voor rich results vereisen een aanvullende test.'},
};
export function AuditEvidence({report}:{report:AuditReport}){
 const pages=report.pages.filter(page=>page.checks?.length);
 return <section className="audit-proof" aria-labelledby="audit-proof-title"><span className="eyebrow">Van score naar bewijs</span><h3 id="audit-proof-title">Dit hebben we daadwerkelijk gecontroleerd.</h3><p>Open een onderzochte pagina. Je ziet wat is gevonden, hoeveel punten dat oplevert en waarom het relevant is. Codevoorbeelden komen uit de ontvangen HTML. Het zijn geen voorgestelde wijzigingen.</p><div className="audit-proof-pages">{pages.map((page,index)=><details key={page.url} open={index===0}><summary><span>{page.title||page.url}</span><small>{page.checks!.filter(check=>check.passed).length} / {page.checks!.length} geslaagd</small></summary><p className="audit-proof-url">{page.url}</p><div className="audit-proof-checks">{page.checks!.map(check=><article key={check.code}><header><strong>{explanations[check.code]?.title||check.code}</strong><span className={check.passed?'audit-proof-pass':'audit-proof-fail'}>{check.passed?'Geslaagd':'Aandacht'} · {check.passed?check.weight:0}/{check.weight} punten</span></header><p>{check.evidence||(check.code==='http'?`HTTP ${page.status}`:'Dit oudere rapport bevat nog geen bewaard voorbeeld. Voer een nieuwe scan uit voor de onderbouwing.')}</p><p className="audit-proof-why">{explanations[check.code]?.why}</p>{check.snippet&&<details className="audit-proof-source"><summary>Bekijk de ontvangen code</summary><pre><code>{check.snippet}</code></pre><small>Fragment uit de response, maximaal 700 tekens.</small></details>}</article>)}</div></details>)}</div><p className="audit-proof-limit">De score beschrijft deze basiscontroles. Zoekwoorden, tekstkwaliteit, snelheid, concurrentie en je werkelijke Google-posities vallen buiten dit cijfer.</p></section>;
}
