import type {AuditReport} from '../../../lib/seo-audit/crawl';
import {auditOverview} from '../../../lib/seo-audit/overview';

export function AuditOverview({report}:{report:AuditReport}){
 const result=auditOverview(report);
 return <div className="audit-dashboard">
  <div className="audit-score-card"><span>Technische basisscore</span><div className="audit-score-ring" style={{background:`conic-gradient(#184bce ${(result.score??0)*3.6}deg, #dfe7e4 0)`}}><strong>{result.score??'—'}<small>{result.score===null?'niet berekend':'van 100'}</small></strong></div><p>{result.passed} van {result.checks} uitgevoerde basiscontroles geslaagd.</p></div>
  <div className="audit-dashboard-stats">{[['Onderzochte URL’s',report.pages.length],['Zonder gevonden noindex',report.pages.filter(p=>p.indexable).length],['Hoge prioriteit',report.findings.filter(f=>f.priority==='hoog').length],['Verbeterpunten',report.findings.filter(f=>f.priority==='middel').length],['Handmatig beoordelen',report.findings.filter(f=>f.priority==='controle').length],['Overgeslagen / onvolledig',report.skipped]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
  <div className="audit-category-overview"><h3>Waar zitten de aandachtspunten?</h3><p>Aantal onderzochte URL’s met een bevinding per onderwerp. Een pagina kan in meerdere onderwerpen meetellen.</p>{result.categories.map(c=><div key={c.name}><span>{c.name}</span><b>{c.count} / {report.pages.length}</b><meter min={0} max={Math.max(1,report.pages.length)} value={c.count} aria-label={`${c.name}: ${c.count} URL’s met bevindingen`}/></div>)}</div>
  <details className="audit-score-explanation"><summary>Hoe werkt deze score?</summary><p>Sitesnit-basisscore v1: geslaagde gewogen controles gedeeld door alle uitgevoerde gewogen controles, afgerond op 100. Bereikbaarheid en afwezigheid van noindex wegen elk 3 punten; een aanwezige titel en maximaal een canonical elk 2; alt-attributen en JSON-LD-syntaxis elk 1. Een fout-URL krijgt alleen de bereikbaarheidstest. Redirects, niet-HTML en overgeslagen pagina’s krijgen geen basisscore.</p><p>De score gaat uit van pagina’s die openbaar gevonden moeten worden: een bewuste noindex is dus geen fout die je zomaar moet verwijderen. Handmatige aandachtspunten veranderen de score niet. Zonder afbeeldingen of JSON-LD betekent een geslaagde controle alleen dat daar geen attribuut- of syntaxisfout is gevonden, niet dat alle nodige inhoud aanwezig is.</p><p>{result.passedWeight} van {result.weight} mogelijke gewogen punten. Dit is geen Google-score, Lighthouse-meting, volledige SEO-audit of bewijs van indexering. Ook 100/100 kan samengaan met aandachtspunten. {report.limited?'De crawl is gedeeltelijk; onbekende pagina’s tellen niet mee.':'De score geldt uitsluitend voor de onderzochte URL’s.'}</p></details>
 </div>;
}
