'use client';
import {useState} from 'react';
import type {AuditReport} from '../../../lib/seo-audit/crawl';
import {CHECK_COUNT,type DetailedCheck} from '../../../lib/seo-audit/check-catalog';
const labels={passed:'Geslaagd',failed:'Verbeterpunt',review:'Zelf beoordelen','not-applicable':'Niet van toepassing','not-tested':'Niet gemeten'};
function CheckList({checks}:{checks:DetailedCheck[]}){
 return <>{[...new Set(checks.map(c=>c.category))].map(category=>{const items=checks.filter(c=>c.category===category),failed=items.filter(c=>c.state==='failed').length;return <details key={category} className="audit-proof-group"><summary>{category}<small>{failed?`${failed} verbeterpunt${failed===1?'':'en'}`:'Bekijk controles'}</small></summary><div className="audit-proof-checks">{items.map(c=><article key={c.id}><header><strong>{c.title}</strong><span className={c.state==='failed'?'audit-proof-fail':c.state==='passed'?'audit-proof-pass':''}>{labels[c.state]}</span></header><p>{c.evidence}</p><p className="audit-proof-why">{c.action}</p>{c.source==='HTML'&&c.weight>0&&['passed','failed'].includes(c.state)&&<small>{c.state==='passed'?c.weight:0}/{c.weight} HTML-punten</small>}{c.snippet&&<details className="audit-proof-source"><summary>Ontvangen code bekijken</summary><pre><code>{c.snippet}</code></pre></details>}</article>)}</div></details>})}</>;
}
export function DetailedEvidence({report}:{report:AuditReport}){
 const [search,setSearch]=useState(''),[expanded,setExpanded]=useState(false);
 const matches=report.pages.filter(page=>(page.title+' '+page.url).toLowerCase().includes(search.toLowerCase()));
 const visible=expanded?matches:matches.slice(0,6);
 return <section className="audit-proof" aria-labelledby="audit-proof-title"><header className="audit-proof-heading"><div><span className="eyebrow">Het bewijs achter je rapport</span><h3 id="audit-proof-title">Bekijk wat er op je pagina staat.</h3><p>Kies een pagina en open een onderwerp. Je ziet de bevinding, uitleg en waar beschikbaar de ontvangen code.</p></div><span className="audit-count-label">{CHECK_COUNT}<small>controlepunten<br/>60 HTML · 40 mobiel</small></span></header><div className="audit-proof-toolbar"><label htmlFor="audit-page-search">Zoek een onderzochte pagina<input id="audit-page-search" type="search" value={search} placeholder="Bijvoorbeeld contact of diensten" onChange={event=>{setSearch(event.target.value);setExpanded(false)}}/></label><span>{matches.length} pagina{matches.length===1?'':'’s'}</span></div><div className="audit-proof-pages">{visible.map((page,index)=>{const failed=page.detailedChecks?.filter(c=>c.state==='failed').length||0;return <details key={page.url}><summary><span className="audit-page-number" aria-hidden="true">{String(index+1).padStart(2,'0')}</span><span className="audit-page-name">{page.title||page.url}<span>{new URL(page.url).pathname}</span></span><small className={failed?'audit-page-warning':''}>{failed?`${failed} verbeterpunt${failed===1?'':'en'}`:'Geen fouten gevonden'}</small><span className="audit-page-chevron" aria-hidden="true">↗</span></summary><p className="audit-proof-url">{page.url}</p><CheckList checks={page.detailedChecks||[]}/></details>})}</div>{matches.length===0&&<p role="status">Geen onderzochte pagina gevonden met deze zoekterm.</p>}{matches.length>6&&<button type="button" className="audit-more-pages" onClick={()=>setExpanded(!expanded)}>{expanded?'Toon de eerste 6 pagina’s':`Bekijk alle ${matches.length} pagina’s`} <span aria-hidden="true">{expanded?'−':'+'}</span></button>}<details className="audit-lab-evidence"><summary>Mobiele test: metingen en bewijs <small>{report.lab?'Meetgegevens ontvangen':'Nog niet beschikbaar'}</small></summary>{report.lab?<p>{report.lab.finalUrl}<br/>{new Date(report.lab.fetchTime).toLocaleString('nl-NL')} · Lighthouse {report.lab.version}. Gesimuleerde mobiele test; geen meting van echte bezoekers.</p>:<p>{report.labError||'Google heeft geen complete labtest teruggestuurd. Je HTML-resultaten blijven beschikbaar.'}</p>}<CheckList checks={report.labChecks||[]}/></details><p className="audit-proof-limit">We onderzoeken maximaal 20 openbare HTML-pagina’s en meten één startpagina met Lighthouse. Zoekintentie, inhoudelijke expertise, backlinks en je daadwerkelijke Google-posities vallen buiten deze technische scan.</p></section>;
}
