import type {AuditReport} from '../../../lib/seo-audit/crawl';
import {CHECK_COUNT,type DetailedCheck} from '../../../lib/seo-audit/check-catalog';
const labels={passed:'Geslaagd',failed:'Aandacht',review:'Handmatig beoordelen','not-applicable':'Niet van toepassing','not-tested':'Niet onderzocht'};
function CheckList({checks}:{checks:DetailedCheck[]}){
 return <>{[...new Set(checks.map(c=>c.category))].map(category=><details key={category} className="audit-proof-group"><summary>{category} <small>{checks.filter(c=>c.category===category&&c.state==='failed').length} aandachtspunten</small></summary><div className="audit-proof-checks">{checks.filter(c=>c.category===category).map(c=><article key={c.id}><header><strong>{c.title}</strong><span className={c.state==='failed'?'audit-proof-fail':c.state==='passed'?'audit-proof-pass':''}>{labels[c.state]}</span></header><p>{c.evidence}</p><p className="audit-proof-why">{c.action}</p>{c.source==='HTML'&&c.weight>0&&['passed','failed'].includes(c.state)&&<small>{c.state==='passed'?c.weight:0}/{c.weight} HTML-punten</small>}{c.snippet&&<details className="audit-proof-source"><summary>Ontvangen code bekijken</summary><pre><code>{c.snippet}</code></pre></details>}</article>)}</div></details>)}</>;
}
export function DetailedEvidence({report}:{report:AuditReport}){
 return <section className="audit-proof" aria-labelledby="audit-proof-title"><span className="eyebrow">{CHECK_COUNT} verschillende controlepunten</span><h3 id="audit-proof-title">Geen cijfer zonder onderbouwing.</h3><p>60 HTML- en responsecontroles worden per onderzochte pagina beoordeeld. 40 aanvullende Lighthouse-controlepunten gelden voor de gemeten startpagina. Niet ieder punt is op iedere website van toepassing. Herhaling op meerdere pagina’s telt niet als een nieuw type controle.</p><div className="audit-proof-pages">{report.pages.map(page=><details key={page.url}><summary><span>{page.title||page.url}</span><small>{page.detailedChecks?.filter(c=>c.state==='failed').length||0} aandachtspunten</small></summary><p className="audit-proof-url">{page.url}</p><CheckList checks={page.detailedChecks||[]}/></details>)}<details><summary>Mobiele Lighthouse-labtest <small>{report.lab?'Meetgegevens ontvangen':'Onvolledig'}</small></summary>{report.lab?<p>{report.lab.finalUrl}<br/>{new Date(report.lab.fetchTime).toLocaleString('nl-NL')} · Lighthouse {report.lab.version}. Gesimuleerde mobiele test, geen echte bezoekersmeting. De uitkomst kan per meetmoment variëren.</p>:<p>{report.labError||'Geen labtest ontvangen. Er is geen volledige technische score berekend.'}</p>}<CheckList checks={report.labChecks||[]}/></details></div><p>Dit is een technische steekproef. Zoekintentie, deskundigheid van de teksten, concurrentie, backlinks en daadwerkelijke opname in Google vragen een afzonderlijke beoordeling. Een hoge technische score bewijst geen sterke zoekpositie.</p></section>;
}
