import { InlineArrow } from '../../inline-arrow';
import {withPageMetadata,BreadcrumbData} from '../../seo';
import {ToolHelp} from '../tool-help';
import {auditGuides} from '../../../lib/seo-audit/guides';
import {AuditClient} from './audit-client';
import './audit.css';
import {AuditIntro} from './audit-intro';
import {auditCapabilities} from '../../../lib/seo-audit/capabilities';
import {htmlCatalog,lighthouseCatalog} from '../../../lib/seo-audit/check-catalog';
export const metadata=withPageMetadata({title:'Gratis SEO-audit — vind technische problemen per pagina',description:`Scan maximaal ${auditCapabilities.maxPages} pagina’s op noindex, kapotte interne links en metadata. Krijg bewijs en hersteladvies, zonder vragenlijst of verplicht account.`},'/tools/seo-audit');
export default function Page(){return <div className="audit-page"><div className="wrap"><BreadcrumbData items={[{name:'Home',path:'/'},{name:'Tools & checks',path:'/tools'},{name:'SEO-audit',path:'/tools/seo-audit'}]}/></div><AuditIntro/><div className="wrap audit-body"><AuditClient><section className="audit-motion"><h2>Wat krijg je precies terug?</h2><p>Een begrensde HTML-crawl van maximaal {auditCapabilities.maxPages} URL’s op een website. De audit onderzoekt HTTP-statussen, robots-toegang, noindex, titels, descriptions, canonicals, ontbrekende alt-attributen en JSON-LD-syntaxis. Hij vergelijkt metadata en koppelt gevonden 404’s aan verwijzende pagina’s binnen de crawl. De controlelijst bevat {htmlCatalog.length} HTML- en responsepunten en {lighthouseCatalog.length} Lighthouse-punten. Je ziet per punt of het slaagt, aandacht vraagt, niet van toepassing is of niet onderzocht kon worden.</p><p>Dit is geen complete Sitechecker-vervanger. De HTML-crawl rendert geen JavaScript. Daarnaast draait een afzonderlijke mobiele Lighthouse-test op je startpagina, met prestaties, toegankelijkheid, best practices en technische SEO. Externe backlinks en de daadwerkelijke Google-index worden niet gemeten. Onbereikbare of uitgesloten pagina’s blijven zichtbaar als niet onderzocht. De bestaande <a href="/tools/website-check">websitecheck met 15 vragen en Lighthouse</a> blijft een afzonderlijke tool voor inhoud en klantpad.</p></section><section className="audit-motion"><span className="eyebrow">Je rapport begrijpen</span><h2>Wat zegt jouw melding eigenlijk?</h2><div className="audit-topic-index">{auditGuides.map((g,i)=><a href={`/tools/seo-audit/${g.slug}`} key={g.slug}><span>0{i+1} / Uitleg & aanpak</span><strong>{g.title}</strong><p>{g.description}</p><span>Lees de aanpak <InlineArrow /></span></a>)}</div></section><section><h2>Gratis beginnen, met duidelijke grenzen.</h2><p>Je krijgt {auditCapabilities.dailyAttempts} scanpoging per netwerk per UTC-dag. Mensen op hetzelfde wifi-netwerk delen die limiet. Het gezamenlijke dagbudget is {auditCapabilities.globalDailyAttempts} pogingen; bij uitputting stopt de tool zonder betaalde uitwijkdienst. Grote websites worden niet volledig onderzocht. Gebruik de resultaten als eerste onderbouwde selectie, niet als keurmerk of rankingbelofte.</p></section><ToolHelp group="seo-audit"/></AuditClient></div></div>;}
