export type SpeedGuideExample={title:string;context:string;headers:string[];rows:string[][];evidence?:string;steps:string[];conclusion:string};
type SpeedGuide={slug:string;label:string;title:string;description:string;answer:string;steps:string[];sections:{title:string;text:string}[];questions:[string,string][];related:string;relatedLabel:string;source:string;sourceLabel?:string;extraSources?:[string,string][];example?:SpeedGuideExample};
export const speedGuides:SpeedGuide[] = [
  {
    example:{
      title:'Van score 62 naar één gerichte controle',
      context:'Fictief rapportvoorbeeld, geen klantmeting. Pagina: https://example.com/diensten · mobiel · 2 oktober 2026, 10:00 UTC. De cijfers zijn bedoeld om het rapport te leren lezen.',
      headers:['Wat zie je?','Voorbeeld','Wat controleer je?'],
      rows:[['Prestatiescore','62 / 100','De samenvatting geeft nog geen oorzaak. Open de laadmetingen.'],['LCP: grootste zichtbare inhoud','4,2 seconden','In dit voorbeeld is de openingsfoto het grootste element. Bekijk wanneer die wordt ontdekt en geladen.'],['TBT: blokkeertijd','180 ms','Controleer genoemde lange taken. Dit is geen INP-meting.'],['CLS: verspringingen','0,04','Er is in deze laadtest weinig verschuiving. Test ook menu en formulier.']],
      evidence:'Voorbeeld van aangetroffen HTML:\n<img src="/openingsfoto.webp" loading="lazy" alt="Werkplaats">',
      steps:['Open in je eigen rapport de bevinding over het grootste zichtbare element of de ontdekking daarvan. De benaming kan per Lighthouse-versie verschillen. Noteer het genoemde element en bestand; ontbreken die, dan is nader onderzoek nodig.','Controleer in de browser of juist deze foto direct in beeld staat en onnodig op lazy loading wacht. Alleen in dát geval kan het uitgestelde laden een gerichte wijziging zijn. Een trage server of blokkerende code vraagt ander herstel.','Meet dezelfde pagina en mobiele omgeving opnieuw, bij voorkeur enkele keren vóór en na één wijziging. Vergelijk de LCP-waarden en hun spreiding. Controleer daarna foto, menu, formulier en cookiekeuze.'],
      conclusion:'Een lagere LCP na de ingreep is bruikbaar bewijs voor deze testsituatie. De score kan tegelijk anders bewegen. Trek er geen conclusie over alle bezoekers, zoekposities of omzet uit.',
    },
    sourceLabel:'Google: hoe de Lighthouse-prestatiescore wordt berekend',
    slug:'pagespeed-score',label:'De score lezen',title:'Wat zegt je PageSpeed-score?',
    description:'Lees de prestatiescore achter je snelheidstest: wat meet Lighthouse, waarom wisselt het cijfer en welke verbetering pak je eerst aan?',
    answer:'De prestatiescore vat vijf laadmetingen samen. Gebruik het cijfer om een probleem op te sporen, en de onderliggende metingen om te bepalen wat je aanpast. Het is geen SEO-cijfer voor je hele website.',
    steps:['Score','Oorzaak','Hercontrole'],
    sections:[
      {title:'Eén pagina, onder testomstandigheden',text:'Lighthouse opent het opgegeven pagina-adres in een gecontroleerde omgeving. De prestatiescore loopt van 0 tot 100 en combineert metingen met verschillende gewichten. Een score van 100 betekent dus niet dat al je pagina’s snel zijn, dat iedereen dezelfde ervaring heeft of dat Google je bovenaan zet. De inhoud en bruikbaarheid van je website blijven afzonderlijke vragen.'},
      {title:'Kijk welke meting de uitkomst verklaart',text:'Verschijnt er lang niets? Kijk naar FCP en naar de eerste documentaanvraag. Komt de belangrijkste inhoud laat? Onderzoek LCP en de bijbehorende audit. Voelt het laden stroperig, dan kan TBT op blokkerende code wijzen. Een hoge CLS vraagt om onderzoek naar verspringende onderdelen. De genoemde bestanden of elementen vormen je aanknopingspunt. Een lage score alleen bewijst geen specifieke oorzaak.'},
      {title:'Een schatting is geen optelsom',text:'Lighthouse kan mogelijke besparingen noemen. Die zijn schattingen binnen de test. Tel ze niet bij elkaar op als gegarandeerde winst: verbeteringen kunnen elkaar beïnvloeden en dezelfde vertraging raken. Verwijder ook niet zomaar scripts die een formulier, cookiekeuze of beveiliging laten werken. Laat de functie na de aanpassing opnieuw doorlopen.'},
      {title:'Zo vergelijk je een verbetering eerlijk',text:'Meet dezelfde URL, hetzelfde apparaat en dezelfde versie meer dan één keer. Bewaar het meetmoment en noteer of een cookiemelding of andere inhoud veranderde. Een uitschieter verdient een herhaling voordat je conclusies trekt. Vergelijk daarna zowel de score als de meting waarop je herstel gericht was. Kijk ook of de pagina nog goed werkt.'},
    ],
    questions:[['Is 90 altijd voldoende?','90 tot 100 valt bij Lighthouse in de goede scoreband. Het is geen garantie voor alle bezoekers of alle pagina’s. Beoordeel daarnaast de concrete metingen, echte bediening en waar beschikbaar bezoekersgegevens.'],['Waarom toont de tool soms geen score?','Een geblokkeerde pagina, timeout, quota of onvolledig API-antwoord kan de meting verhinderen. Zonder geldige meting toont Sitesnit geen cijfer. Dat is geen score van nul.']],
    related:'mobiel-desktop',relatedLabel:'Waarom mobiel en desktop verschillen',
    source:'https://developer.chrome.com/docs/lighthouse/performance/performance-scoring',
  },
  {
    example:{"title":"Dezelfde dienstenpagina, twee verschillende meetomgevingen","context":"Fictieve vergelijking, geen werkelijk klantresultaat. Beide tests vragen https://example.com/diensten aan en eindigen op datzelfde adres. De websiteversie is gelijk.","headers":["Waarneming","Mobiel","Desktop"],"rows":[["Meetmoment (2 oktober 2026, UTC)","10:00","10:01"],["Prestatiescore","62 / 100","94 / 100"],["LCP: grootste zichtbare inhoud","4,2 s · openingsfoto","1,8 s · openingsfoto"],["TBT: blokkeertijd","420 ms","70 ms"],["CLS: verspringingen","0,04","0,03"]],"steps":["Kies Beide vergelijken in de snelheidstest. Controleer eerst aangevraagd adres, eindadres en tijdstip. Verschillen de eindadressen, onderzoek dan eerst de doorverwijzing; je vergelijkt anders mogelijk andere inhoud.","Open bij mobiel de bevinding over de foto en de blokkerende code. Controleer of de mobiele browser een passende beeldvariant ontvangt en welke scripts daadwerkelijk lange taken veroorzaken. De tabel alleen wijst nog geen schuldige aan.","Pas één aangetoond probleem aan en herhaal de mobiele meting op dezelfde versie en URL. Houd desktop apart als controle. Open de pagina ook op een telefoon en probeer menu, scrollen en formulier."],"conclusion":"Het verschil is aanleiding voor onderzoek, geen gemeten vertraging op jouw eigen telefoon. Een desktopscore van 94 maakt de mobiele kant niet automatisch goed."},
    slug:'mobiel-desktop',label:'Apparaten vergelijken',title:'Waarom is je mobiele website trager?',
    description:'Vergelijk mobiele en desktopmetingen zonder verkeerde conclusies. Begrijp testomstandigheden, responsive beelden en de invloed van scripts.',
    answer:'Mobiel en desktop gebruiken andere Lighthouse-testomstandigheden. Een lagere mobiele score kan wijzen op zwaar laadwerk, maar vergelijk steeds met hetzelfde apparaat voordat je een verbetering beoordeelt.',
    steps:['Zelfde URL','Zelfde apparaat','Nieuwe meting'],
    sections:[
      {title:'Een andere test, een ander cijfer',text:'De mobiele test simuleert beperktere omstandigheden dan de desktoptest. Ook het schermformaat verschilt. Daardoor kan andere inhoud zichtbaar zijn en kan een ander element het grootste zichtbare element worden. Een desktopscore van 95 en een mobiele score van 65 zijn daarom geen tegenstrijdige resultaten. Het verschil is een reden om de mobiele audits te lezen.'},
      {title:'Bekijk wat een telefoon echt moet laden',text:'Een kleinere afbeelding op het scherm is niet automatisch een kleiner downloadbestand. Controleer of de browser een geschikte beeldvariant ontvangt, of belangrijke inhoud direct gevonden wordt en of ruimte voor beelden is gereserveerd. Geef een belangrijke eerste afbeelding niet zonder onderzoek lazy loading: dat kan de start juist vertragen. Beelden lager op de pagina kunnen daar wel baat bij hebben.'},
      {title:'Code kan meer tijd kosten dan het downloaden',text:'Een script moet na het downloaden ook worden uitgevoerd. Veel code of lange taken kunnen op een gesimuleerd mobiel apparaat zwaar doorwegen. Kijk welke bestanden Lighthouse daadwerkelijk noemt. Stel alleen onderdelen uit die de eerste weergave niet nodig heeft en controleer daarna menu, formulieren en toestemming. Een snellere score met kapotte bediening is geen verbetering.'},
      {title:'Meet opnieuw en gebruik ook een echte telefoon',text:'Begin met de mobiele test van je belangrijkste landingspagina. Herhaal na een gerichte wijziging met dezelfde apparaatkeuze. Gebruik een desktoptest als afzonderlijke controle, niet als bewijs dat mobiel is opgelost. Open de pagina daarnaast op een telefoon: lees tekst, scroll, open het menu en verstuur een veilige test via je afgesproken testomgeving. Een labtest beoordeelt niet iedere gebruikershandeling.'},
    ],
    questions:[['Is dit een meting op mijn eigen telefoon?','Nee. Google voert de Lighthouse-test uit. De telefoon of computer waarmee jij de Sitesnit-tool opent, bepaalt de testomgeving niet. Je apparaatkeuze in het formulier doet dat.'],['Kan ik mobiel en desktop tegelijk laten testen?','Ja. Kies Beide vergelijken voor twee afzonderlijke metingen met eigen resultaten en meetmomenten. Een mislukte kant kun je apart herhalen. Twee metingen gebruiken twee verzoeken binnen de gedeelde scanlimiet.']],
    related:'core-web-vitals',relatedLabel:'Labmetingen en echte bezoekerservaring onderscheiden',
    source:'https://developers.google.com/speed/docs/insights/v5/about',
  },
  {
    example:{"title":"Een goede labtest, maar nog geen bezoekersoordeel","context":"Fictief leesvoorbeeld. Voor https://example.com/diensten toont een labtest LCP 2,1 s, TBT 80 ms en CLS 0,02. Bij de bezoekersgegevens staat dat er onvoldoende data voor deze URL is.","headers":["Gegeven","Wat weet je?","Volgende controle"],"rows":[["LCP: laden","De grootste zichtbare inhoud verschijnt in deze labtest na 2,1 s.","Zoek bij bezoekersgegevens naar dezelfde URL én hetzelfde apparaat."],["INP: reactie op interactie","Niet gemeten door deze laadtest. TBT 80 ms is geen INP 80 ms.","Bekijk beschikbare INP-velddata en probeer de echte handelingen."],["CLS: verschuivingen","0,02 tijdens deze laadtest. Verschuivingen later in het bezoek kunnen ontbreken.","Open bijvoorbeeld het menu en toon formulierfouten."],["Alleen gegevens voor de origin","Een beeld van de hele herkomst, bijvoorbeeld https://example.com.","Gebruik dit niet als exacte uitslag voor /diensten."],["Geen URL- of origindata","De ervaring van echte bezoekers is hiermee onbekend.","Gebruik labtests en handmatige controles; vul geen groen oordeel in."]],"steps":["Open PageSpeed Insights van Google voor je openbare pagina en bekijk het blok over echte gebruikers. Controleer of het de URL of de hele origin betreft, welk apparaat geselecteerd is en welke meetperiode wordt getoond.","Heb je toegang tot Search Console? Open Core Web Vitals, kies mobiel of desktop, open een probleemgroep en bekijk de voorbeeld-URL’s. Groepsgegevens zijn een aanknopingspunt; ze bewijzen niet dat elke URL precies dezelfde oorzaak heeft.","Onderzoek een representatieve URL met een labtest en controleer de genoemde interactie of verschuiving zelf. Noteer de aanpassing. Gebruik daarna een nieuwe labtest voor directe hercontrole; bezoekersgegevens over een langere meetperiode veranderen niet onmiddellijk."],"conclusion":"LCP, INP en CLS moeten alle drie met geschikte bezoekersgegevens worden beoordeeld. Sitesnit haalt die veldgegevens niet op en verklaart een website dus niet geslaagd op basis van deze labtest."},
    sourceLabel:'Google: definities en grenzen van Core Web Vitals',
    extraSources:[['Open Google PageSpeed Insights','https://pagespeed.web.dev/'],['Google: het Core Web Vitals-rapport in Search Console','https://support.google.com/webmasters/answer/9205520']],
    slug:'core-web-vitals',label:'Lab of echte bezoekers?',title:'Core Web Vitals en je snelheidstest',
    description:'Wat vertellen LCP, CLS en INP over bezoekerservaring? Lees waarom een Lighthouse-labtest geen volledige Core Web Vitals-beoordeling is.',
    answer:'Core Web Vitals gaan over laden, interactie en visuele stabiliteit. Deze snelheidstest toont een Lighthouse-labmeting. Daarmee kun je oorzaken onderzoeken, maar je stelt niet vast dat je website bij echte bezoekers voor alle Core Web Vitals slaagt.',
    steps:['Laden: LCP','Interactie: INP','Stabiliteit: CLS'],
    sections:[
      {title:'Drie verschillende vragen',text:'LCP beschrijft wanneer het grootste zichtbare inhoudselement verschijnt. INP kijkt naar de respons op interacties tijdens een bezoek. CLS beschrijft onverwachte verschuivingen in de layout. De goede grenzen zijn respectievelijk maximaal 2,5 seconden, 200 milliseconden en 0,1. Bij veldgegevens gaat de beoordeling om het 75e percentiel van gemeten bezoeken, afzonderlijk voor mobiel en desktop. Niet om jouw beste losse test.'},
      {title:'Wat deze tool wel laat zien',text:'De labtest meet onder meer LCP en CLS tijdens het laden en TBT als signaal voor blokkerende taken. TBT is geen vervanger voor een werkelijk gemeten INP. Een pagina kan tijdens het laden stabiel zijn en later toch verspringen, bijvoorbeeld na een interactie. Gebruik de labuitkomst om concrete code of beelden te onderzoeken en test de belangrijke handelingen daarnaast zelf.'},
      {title:'Waar bezoekersgegevens vandaan komen',text:'Google kan via het Chrome User Experience Report gegevens tonen van echte Chrome-bezoeken die aan de voorwaarden voldoen. Niet elke URL heeft voldoende gegevens. Soms is alleen informatie voor de hele origin beschikbaar. Die mag je niet presenteren als exacte meting van één pagina. De Sitesnit-snelheidstest haalt die veldgegevens niet op en geeft daarom geen oordeel “Core Web Vitals geslaagd”.'},
      {title:'Een wijziging zie je niet overal direct terug',text:'Een nieuwe labtest kan je aanpassing meteen onderzoeken. Veldgegevens beschrijven een meetperiode en bevatten ook bezoeken aan een eerdere versie. Noteer daarom wanneer je iets hebt aangepast en welk rapport je vergelijkt. Gebruik Search Console voor beschikbare Core Web Vitals-groepen en controleer de betrokken URL’s. Ontbrekende gegevens betekenen onbekend, niet goed of slecht.'},
    ],
    questions:[['Betekent geen bezoekersdata dat mijn website langzaam is?','Nee. Er kunnen te weinig geschikte bezoeken zijn om gegevens te publiceren. Je kunt wel een labtest uitvoeren en de pagina handmatig controleren.'],['Garanderen goede Core Web Vitals een hogere positie?','Nee. Een goede pagina-ervaring is waardevol, maar zoekresultaten hangen ook samen met inhoud en relevantie. Een technische meting is geen voorspelling van verkeer of omzet.']],
    related:'pagespeed-score',relatedLabel:'De prestatiescore op de juiste manier lezen',
    source:'https://web.dev/articles/vitals',
  },
];
export const speedQuestions = [
  ['Is de snelheidstest gratis?','Ja. Je hebt geen account of e-mailadres nodig. We gebruiken Google PageSpeed Insights. De beschikbaarheid hangt af van het API-quotum. Bij drukte kun je later opnieuw proberen.'],
  ['Wat wordt er getest?','Eén openbaar pagina-adres met Lighthouse, op mobiel, desktop of beide afzonderlijk. Je krijgt een prestatiescore, laadmetingen en de beschikbare bevindingen. Het is geen crawl van je hele website en geen meting van echte bezoekers.'],
  ['Wat gebeurt er met mijn websiteadres?','Na het starten sturen we het openbare pagina-adres via onze server naar Google. Gebruik geen privélink of adres met parameters. Het resultaat blijft in dit tabblad en wordt niet automatisch een contactaanvraag.'],
] as const;
