import { Breadcrumbs, withPageMetadata, JsonLd } from '../seo';
import { Arrow, Eyebrow, Cta } from '../ui';
import { site } from '../site-data';
import '../guides.css';
export const metadata=withPageMetadata({},'/seo-venlo');

export default function Page(){return <article className="guide-page">
  <Breadcrumbs items={[{name:'Home',path:'/'},{name:'SEO & vindbaarheid',path:'/diensten/seo'},{name:'SEO Venlo',path:'/seo-venlo'}]}/>
  <JsonLd data={{'@context':'https://schema.org','@type':'Service','@id':`${site.origin}/seo-venlo#service`,name:'SEO voor bedrijven in Venlo',description:'Technische en inhoudelijke verbeteringen vanuit Baarlo, met vooraf afgebakende werkzaamheden.',provider:{'@id':`${site.origin}/#organization`},areaServed:{'@type':'City',name:'Venlo'}}}/>
  <header className="wrap guide-intro"><div><Eyebrow>Sitesnit / Vanuit Baarlo, voor Venlo</Eyebrow><h1>Vindbaar voor de vraag die bij jouw bedrijf past.</h1><p>Een dienstenpagina moet uitleggen wat je doet én aansluiten op wat je klant zoekt. Sitesnit helpt bedrijven in Venlo met de inhoud, structuur en technische basis van hun website. Je spreekt rechtstreeks met Kay, vanuit Baarlo.</p><a className="button" href="/contact?dienst=seo">Bespreek je vindbaarheid <Arrow/></a></div><div className="guide-takeaway"><span>Een concreet vertrekpunt</span><strong>Welke vraag stelt je klant voordat die bij jou terechtkomt?</strong><div aria-hidden="true">?<span>→</span>!</div></div></header>
  <div className="wrap guide-layout"><aside className="guide-contents"><nav aria-label="Op deze pagina"><a href="#onderzoek">Waar zit de vraag?</a><a href="#lokaal">Lokaal zonder plaatsnamenlijst</a><a href="#uitvoeren">Wat kan Sitesnit doen?</a><a href="#afspraken">Samenwerking en kosten</a></nav></aside><div className="guide-body">
    <section id="onderzoek"><h2>Eerst begrijpen waarom je pagina niet helpt</h2><p>We beginnen bij je aanbod en de pagina’s die daarvoor belangrijk zijn. Heb je toegang tot Search Console, dan kunnen de beschikbare zoekvragen en paginaresultaten richting geven. Ontbreken gegevens, dan vullen we die niet in met een verzonnen zoekvolume of score.</p><p>Soms gaat het om een technisch probleem. Soms is een pagina wel bereikbaar, maar zegt zij weinig over de opdracht die een bezoeker wil laten uitvoeren. Dat vraagt een andere oplossing dan alleen een nieuwe titel.</p><a className="text-link" href="/website-niet-gevonden-google">Onderzoek waarom je website niet wordt gevonden <Arrow/></a></section>
    <section id="lokaal"><h2>Een regionale pagina moet iets toevoegen</h2><p>Een installatiebedrijf dat in Venlo werkt kan uitleggen welke werkzaamheden het daar uitvoert, hoe een opname verloopt en welke eigen projecten passen. Alleen ‘Venlo’ toevoegen aan een algemene tekst helpt een bezoeker nauwelijks kiezen.</p><div className="guide-example"><h3>Fictief tekstvoorbeeld: van brede claim naar een concrete vraag</h3><p><strong>Weinig houvast:</strong> ‘Jouw specialist in duurzame installaties in Venlo.’</p><p><strong>Meer informatie:</strong> ‘Een warmtepomp voor je bestaande woning in Venlo? Tijdens een opname bekijken we isolatie, beschikbare ruimte en je huidige verwarming. Daarna bespreken we welk systeem past en welke aanpassingen nodig zijn.’</p><p>Die tweede tekst is alleen passend als het bedrijf deze opname ook echt uitvoert. De dienst, werkwijze en grenzen maken het verschil; de plaatsnaam geeft context.</p></div><h3>Wat ik bij een eerste gesprek wil weten</h3><ul className="guide-steps"><li>Welke opdrachten wil je in Venlo en omgeving aannemen, en welke vallen buiten je werkgebied?</li><li>Welke vragen stellen klanten vóór ze een offerte aanvragen?</li><li>Welke eigen projecten, foto’s en toelichtingen mogen op de pagina?</li><li>Wat gebeurt er na een aanvraag, en staat dat duidelijk op je website?</li></ul><p>Sitesnit werkt vanuit Baarlo. We gebruiken jouw werkgebied en ervaring om een pagina te maken die aansluit op je dagelijkse praktijk.</p></section>
    <section id="uitvoeren"><h2>Verbeter de website die je al hebt</h2><p>Een SEO-vraag is geen automatische reden voor een nieuwe website. Goede inhoud en bruikbare adressen blijven behouden waar dat past. Als de structuur of techniek de verbetering belemmert, bespreken we eerst welke verandering nodig is.</p><ul className="guide-steps"><li>Dienstenpagina’s verduidelijken met aanpak, grenzen en passende voorbeelden.</li><li>Interne routes herstellen zodat uitleg, werk en contact logisch op elkaar aansluiten.</li><li>Vastgestelde technische fouten oplossen en opnieuw controleren.</li><li>Een afgebakende werklijst maken voor vervolgwerk.</li></ul><p>In de Beurswijzer-case zie je hoe Sitesnit uitleg en interactieve hulpmiddelen samenbrengt. De case toont ontwerp- en inhoudskeuzes, geen onbewezen zoekresultaten.</p><a className="text-link" href="/projecten/beurswijzer">Bekijk de Beurswijzer-case <Arrow/></a></section>
    <section id="afspraken"><h2>Eenmalig verbeteren of blijven bijwerken?</h2><p>Voor een concrete eerste opdracht kun je SEO-optimalisatie bespreken. Voor een terugkerende werklijst is er SEO-onderhoud. Nieuwe artikelen, functies en externe abonnementen bespreken we afzonderlijk.</p><p>We leggen de werkzaamheden en prijs vast voordat we beginnen en houden rekening met je bestaande onderhoudspakket. Een gesprek kan op werkdagen van 18:00 tot 21:30 of in het weekend; je voorkeursmoment is optioneel en wordt samen bevestigd.</p><a className="text-link" href="/diensten/seo-optimalisatie">Eenmalige SEO-optimalisatie <Arrow/></a><br/><a className="text-link" href="/diensten/seo-onderhoud">Doorlopend SEO-onderhoud <Arrow/></a></section>
  </div></div><section className="wrap guide-next"><Eyebrow>Zelf eerst je vertrekpunt bekijken</Eyebrow><h2>Wat vraagt jouw website om aandacht?</h2><p>De websitecheck combineert 15 inhoudelijke vragen met een mobiele Lighthouse-meting van één pagina. Je uitkomst kan mee naar een gesprek; het is geen volledige site-audit.</p><a className="button" href="/tools/website-check">Check je website <Arrow/></a></section><Cta title="Je aanbod verdient" accent="een duidelijke plek."/>
</article>}
