import { Breadcrumbs, withPageMetadata, JsonLd } from '../seo';
import { Arrow, Eyebrow, Cta } from '../ui';
import { site } from '../site-data';
import '../guides.css';
import '../guide-refinements.css';
export const metadata=withPageMetadata({},'/seo-venlo');

export default function Page(){return <article className="guide-page">
  <Breadcrumbs items={[{name:'Home',path:'/'},{name:'SEO & vindbaarheid',path:'/diensten/seo'},{name:'SEO Venlo',path:'/seo-venlo'}]}/>
  <JsonLd data={{'@context':'https://schema.org','@type':'Service','@id':`${site.origin}/seo-venlo#service`,name:'SEO voor bedrijven in Venlo',description:'Technische en inhoudelijke verbeteringen vanuit Baarlo, met vooraf afgebakende werkzaamheden.',provider:{'@id':`${site.origin}/#organization`},areaServed:{'@type':'City',name:'Venlo'}}}/>
  <header className="wrap guide-intro"><div><Eyebrow>Sitesnit / Vanuit Baarlo, voor Venlo</Eyebrow><h1>SEO voor ondernemers in Venlo.</h1><p>Ik help je bestaande website technisch en inhoudelijk verbeteren. Van een concrete fout tot dienstenpagina’s die duidelijker moeten worden. Je spreekt rechtstreeks met Kay in Baarlo. De werkzaamheden en prijs worden vooraf afgesproken.</p><a className="button" href="/contact?dienst=seo">Bespreek je website <Arrow/></a><br/><a className="text-link" href="/tools/seo-audit">Controleer eerst je technische SEO <Arrow/></a></div><div className="guide-takeaway"><span>Een concreet vertrekpunt</span><strong>Welke vraag stelt je klant voordat die bij jou terechtkomt?</strong><div aria-hidden="true">?<span>→</span>!</div></div></header>
  <div className="wrap guide-layout"><aside className="guide-contents"><nav aria-label="Op deze pagina"><a href="#onderzoek">Waar zit de vraag?</a><a href="#lokaal">Zo maak je een dienst concreter</a><a href="#uitvoeren">Wat kan Sitesnit doen?</a><a href="#afspraken">Samenwerking en kosten</a></nav></aside><div className="guide-body">
    <section id="onderzoek"><h2>Eerst begrijpen waarom je pagina niet helpt</h2><p>We beginnen bij je aanbod en de pagina’s die daarvoor belangrijk zijn. Heb je toegang tot Search Console, dan kunnen de beschikbare zoekvragen en paginaresultaten richting geven. Ontbreken gegevens, dan vullen we die niet in met een verzonnen zoekvolume of score.</p><p>Soms gaat het om een technisch probleem. Soms is een pagina wel bereikbaar, maar zegt zij weinig over de opdracht die een bezoeker wil laten uitvoeren. Dat vraagt een andere oplossing dan alleen een nieuwe titel.</p><a className="text-link" href="/website-niet-gevonden-google">Onderzoek waarom je website niet wordt gevonden <Arrow/></a></section>
    <section id="lokaal"><h2>Zo maak je een dienst concreter</h2><p>Een installatiebedrijf dat in Venlo werkt kan uitleggen welke werkzaamheden het daar uitvoert, hoe een opname verloopt en welke eigen projecten passen. Alleen ‘Venlo’ toevoegen aan een algemene tekst helpt een bezoeker nauwelijks kiezen.</p><div className="guide-example"><h3>Fictief tekstvoorbeeld: van brede claim naar een concrete vraag</h3><p><strong>Weinig houvast:</strong> ‘Jouw specialist in duurzame installaties in Venlo.’</p><p><strong>Meer informatie:</strong> ‘Een warmtepomp voor je bestaande woning in Venlo? Tijdens een opname bekijken we isolatie, beschikbare ruimte en je huidige verwarming. Daarna bespreken we welk systeem past en welke aanpassingen nodig zijn.’</p><p>Die tweede tekst is alleen passend als het bedrijf deze opname ook echt uitvoert. De dienst, werkwijze en grenzen maken het verschil. De plaatsnaam geeft context.</p></div><h3>Wat ik bij een eerste gesprek wil weten</h3><ul className="guide-steps"><li>Welke opdrachten wil je in Venlo en omgeving aannemen, en welke vallen buiten je werkgebied?</li><li>Welke vragen stellen klanten voor ze een offerte aanvragen?</li><li>Welke eigen projecten, foto’s en toelichtingen mogen op de pagina?</li><li>Wat gebeurt er na een aanvraag, en staat dat duidelijk op je website?</li></ul><p>Sitesnit werkt vanuit Baarlo. We gebruiken jouw werkgebied en ervaring om een pagina te maken die aansluit op je dagelijkse praktijk.</p></section>
    <section id="uitvoeren"><h2>Verbeter de website die je al hebt</h2><p>Een SEO-vraag is geen automatische reden voor een nieuwe website. Goede inhoud en bruikbare adressen blijven behouden waar dat past. Als de structuur of techniek de verbetering belemmert, bespreken we eerst welke verandering nodig is.</p><ul className="guide-steps"><li>Dienstenpagina’s verduidelijken met aanpak, grenzen en passende voorbeelden.</li><li>Interne routes herstellen zodat uitleg, werk en contact logisch op elkaar aansluiten.</li><li>Vastgestelde technische fouten oplossen en opnieuw controleren.</li><li>Een afgebakende werklijst maken voor vervolgwerk.</li></ul><p>In de <a className="inline-context-link" href="/projecten/beurswijzer">Beurswijzer-case</a> zie je hoe Sitesnit uitleg en interactieve hulpmiddelen samenbrengt. De case toont ontwerp- en inhoudskeuzes, geen onbewezen zoekresultaten.</p></section>
    <section id="afspraken"><h2>Eenmalig verbeteren of blijven bijwerken?</h2><p>Voor een concrete eerste opdracht kun je <a className="inline-context-link" href="/diensten/seo-optimalisatie">SEO-optimalisatie</a> bespreken. Voor een terugkerende werklijst is er <a className="inline-context-link" href="/diensten/seo-onderhoud">SEO-onderhoud</a>. Nieuwe artikelen, functies en externe abonnementen bespreken we afzonderlijk.</p><p>We leggen de werkzaamheden en prijs vast voordat we beginnen en houden rekening met je bestaande onderhoudspakket. Een gesprek kan op werkdagen van 18:00 tot 21:30 of in het weekend. Je voorkeursmoment is optioneel en wordt samen bevestigd.</p></section>
  </div></div><section className="wrap guide-next"><Eyebrow>Zelf eerst je vertrekpunt bekijken</Eyebrow><h2>Welke technische punten vragen aandacht?</h2><p>De gratis SEO-audit toont de onderzochte pagina’s, gevonden signalen en beperkingen. Je kunt het rapport zelf gebruiken of bespreken welke herstelacties passen.</p><a className="button" href="/tools/seo-audit">Start de technische SEO-audit <Arrow/></a><p>Twijfel je vooral over je boodschap of de route naar contact? De <a href="/tools/website-check">Websitecheck</a> helpt die vragen beoordelen, met een aanvullende meting van één pagina.</p></section><Cta title="Je aanbod verdient" accent="een duidelijke plek."/>
</article>}
