import { withPageMetadata, BreadcrumbData } from '../seo';
import { Arrow, Eyebrow } from "../ui";
import { WorkPair } from "../work-pair";
import { ServiceCanvas } from "../service-canvas";
import "../expansion.css";
import "../work-story.css";
import "../service-experience.css";
import type { Metadata } from "next";

export const metadata: Metadata = withPageMetadata({alternates:{canonical:"/diensten"}}, '/diensten');

export default function Diensten(){return <div className="services-story services-overview">
  <BreadcrumbData items={[{name:'Home',path:'/'},{name:'Diensten',path:'/diensten'}]} />
  <section className="wrap service-opening"><Eyebrow>Diensten / Venlo & Limburg</Eyebrow><h1>Jouw volgende stap.<br/><em>Goed ontworpen.</em></h1><div className="service-opening-bottom"><p>Een eigen gezicht online. Meer mensen bereiken. Of minder handwerk in je bedrijf. Ontdek wat er mogelijk is en lees verder over wat bij jouw plannen past.</p><a className="text-link" href="#webdesign">Ontdek wat we doen ↓</a></div></section>
  <section className="overview-design" id="webdesign"><div className="wrap overview-design-grid"><div className="overview-topic-copy"><Eyebrow>01 / Webdesign & webshops</Eyebrow><h2>Een eigen gezicht.<br/><em>Een sterke website.</em></h2><p>Van de eerste indruk tot een aanvraag of bestelling. We verbinden je merk, verhaal en functies in een website die op ieder scherm klopt.</p><ul className="overview-scope"><li><b>Websites & webshops</b><span>Een onepager, bedrijfswebsite of eigen online winkel.</span></li><li><b>Merk, tekst & beeld</b><span>Logo, kleuren, copywriting en foto’s of video via een partner.</span></li><li><b>Functies op maat</b><span>Van contactformulier tot reservering of klantomgeving.</span></li></ul><a className="button" href="/diensten/webdesign">Ontdek webdesign & webshops<Arrow/></a></div><WorkPair/></div></section>
  <section className="overview-apps" id="apps"><div className="wrap overview-design-grid"><div className="overview-topic-copy"><Eyebrow>02 / Apps & webapps</Eyebrow><h2>Jouw idee.<br/><em>Ook als app.</em></h2><p>Een afspraak beheren, een aanvraag volgen of onderweg iets doorgeven. We maken apps voor iPhone en Android, met voorbereiding voor de App Store en Google Play. Een klantportaal in de browser kan daar onderdeel van zijn.</p><ul className="overview-scope"><li><b>Apps voor iPhone & Android</b><span>Een eigen toepassing op de telefoon van je klant of medewerker.</span></li><li><b>Webapps & klantportalen</b><span>Inloggen, gegevens delen en samenwerken via de browser.</span></li><li><b>Van ontwerp tot publicatie</b><span>Schermen, functies, testen en de afgesproken stappen naar de appwinkels.</span></li></ul><a className="button" href="/diensten/apps">Ontdek apps voor iPhone & Android<Arrow/></a><a className="text-link" href="/diensten/webapps">Of bekijk webapps & klantportalen<Arrow/></a></div><ServiceCanvas kind="apps" animated/></div></section>
  <section className="overview-reach" id="seo"><div className="wrap overview-reach-grid"><div className="overview-topic-copy"><Eyebrow>03 / SEO, content & social media</Eyebrow><h2>In beeld.<br/><em>Bij de juiste mensen.</em></h2><p>Wat zoeken je klanten en wat willen ze weten? We maken je verhaal vindbaar, begrijpelijk en herkenbaar. Voor Venlo en omstreken, heel Limburg of een groter werkgebied.</p><a className="button" href="/diensten/seo">Ontdek SEO & content<Arrow/></a></div><div className="overview-reach-topics"><article data-reveal><span>01</span><div><h3>Gevonden worden.</h3><p>Zoekvragen, dienstenpagina’s, lokale vindbaarheid en een goede technische basis.</p></div></article><article data-reveal><span>02</span><div><h3>Iets te vertellen hebben.</h3><p>Heldere websiteteksten, sterke artikelen en regelmatig nieuwe blogs.</p></div></article><article data-reveal><span>03</span><div><h3>Herkenbaar blijven.</h3><p>Dezelfde basisinhoud, passend gemaakt voor Instagram, Facebook en LinkedIn.</p></div></article><div className="overview-reading-route" aria-label="De route van je bezoeker"><span>Zoeken</span><Arrow/><span>Lezen</span><Arrow/><b>Contact</b></div></div></div></section>
  <section className="overview-automation" id="ai-automatisering"><div className="wrap overview-automation-grid"><div className="overview-topic-copy"><Eyebrow>04 / Tools & automatisering</Eyebrow><h2>Een slim hulpmiddel.<br/><em>Meer tijd over.</em></h2><p>Maak ingewikkelde informatie eenvoudig of geef terugkerend werk uit handen. We bouwen rondom de taak: van een slimme aanvraag tot gegevens die automatisch op de juiste plek komen.</p><ul className="overview-tool-topics"><li>Rekentools & calculators</li><li>Contact- en aanvraagformulieren</li><li>AI-assistenten & documentverwerking</li><li>Backend, API’s & softwarekoppelingen</li></ul><a className="button" href="/diensten/ai-automatisering">Ontdek tools & automatisering<Arrow/></a></div><div className="overview-flow" data-scroll-scene="unfold"><div className="overview-flow-heading"><span>Een voorbeeld van wat mogelijk is</span><strong>Van aanvraag.<br/><em>Naar een volgende stap.</em></strong></div><ol data-scene-target>{[["Je klant vult in","Een duidelijk formulier vraagt wat je nodig hebt."],["De informatie krijgt een plek","Gegevens worden gecontroleerd en aan je software gekoppeld."],["Jij kunt verder","Een dossier, taak of conceptantwoord staat klaar voor je controle."]].map(([title,text],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></div></section>
  <section className="overview-care-chapter" id="onderhoud"><div className="wrap overview-care-grid"><div className="overview-topic-copy"><Eyebrow>05 / Ook na de lancering</Eyebrow><h2>Goed begonnen.<br/><em>Blijvend verzorgd.</em></h2><p>Je website blijft onderdeel van je bedrijf. Geef de techniek uit handen, laat bestaande teksten verbeteren of kies een vast ritme voor nieuwe inhoud.</p><ul className="overview-scope"><li><b>Online & technisch verzorgd</b><span>Hosting, maandelijkse controles en herstel van technische fouten.</span></li><li><b>Je bestaande website bijhouden</b><span>Doorlopende SEO-verbeteringen aan teksten en code.</span></li><li><b>Nieuwe inhoud op een vast ritme</b><span>Blogs en berichten voor Instagram, Facebook of LinkedIn.</span></li></ul><a className="button" href="/diensten/onderhoud-hosting">Onderhoud, hosting & maandpakketten<Arrow/></a><div className="care-services-links"><a className="text-link" href="/diensten/content#maandpakketten">Blogs laten verzorgen<Arrow/></a><a className="text-link" href="/diensten/social-media#maandpakketten">Social media uitbesteden<Arrow/></a></div></div><ServiceCanvas kind="onderhoud-hosting" animated/></div></section>
  <section className="wrap services-closing-note"><span>Waar wil jij mee verder?</span><strong>We maken het concreet.</strong><p>Je hoeft nog geen dienst of pakket te kiezen. Vertel wat je wilt bereiken; dan kijken we welke onderdelen daarbij passen.</p><a className="button" href="/contact">Bespreek je plannen<Arrow/></a></section>
</div>;}

