import { withPageMetadata, BreadcrumbData } from '../seo';
import { Arrow, Eyebrow } from "../ui";
import { WorkPair } from "../work-pair";
import { ServiceCanvas } from "../service-canvas";
import "../expansion.css";
import "../work-story.css";
import "../service-experience.css";
import "./overview-intents.css";
import type { Metadata } from "next";

export const metadata: Metadata = withPageMetadata({alternates:{canonical:"/diensten"}}, '/diensten');

export default function Diensten(){return <div className="services-story services-overview">
  <BreadcrumbData items={[{name:'Home',path:'/'},{name:'Diensten',path:'/diensten'}]} />
  <section className="wrap service-opening"><Eyebrow>Diensten / Sitesnit</Eyebrow><h1>Wat wil je aan je<br/><em>website laten doen?</em></h1><div className="service-opening-bottom"><p>Een nieuwe website, gerichte verbeteringen of beheer na de oplevering: begin bij wat je nodig hebt. Hieronder zie je wat ik met Sitesnit maak en uitvoer. Apps, klantomgevingen en koppelingen hebben een eigen route.</p><a className="text-link" href="#kies-je-vraag">Kies jouw vertrekpunt ↓</a></div></section>
  <nav className="wrap services-intent-nav" id="kies-je-vraag" aria-label="Kies wat je bedrijf nodig heeft">
    {[
      ['webdesign','Een nieuwe of betere website','Je aanbod uitleggen, aanvragen ontvangen of online verkopen.'],
      ['seo','Meer relevante mensen bereiken','Gevonden worden met duidelijke pagina’s en bruikbare inhoud.'],
      ['ai-automatisering','Minder werk met losse systemen','Aanvragen ordenen, gegevens overzetten en handwerk verminderen.'],
      ['apps','Een eigen app of klantomgeving','Klanten of medewerkers iets laten regelen en terugvinden.'],
      ['onderhoud','Je website laten verzorgen','Techniek, nieuwe inhoud en inzicht na de lancering.'],
    ].map(([id,title,text],i)=><a href={`#${id}`} key={id}><span>0{i+1}</span><div><strong>{title}</strong><p>{text}</p></div><Arrow/></a>)}
  </nav>
  <section className="overview-design" id="webdesign"><div className="wrap overview-design-grid"><div className="overview-topic-copy"><Eyebrow>01 / Je website laten maken</Eyebrow><h2>Laat zien wat je doet.<br/><em>Maak contact makkelijk.</em></h2><p>Begin je voor jezelf, groeit je aanbod of past je huidige website niet meer? Ik vertaal wat jouw bedrijf doet naar duidelijke pagina’s, een eigen ontwerp en een logische route naar contact of bestellen.</p><ul className="overview-scope"><li><b>Websites & webshops</b><span>Een onepager, bedrijfswebsite of eigen online winkel.</span></li><li><b>Merk, tekst & beeld</b><span>Een herkenbare stijl en duidelijke teksten; beeld via een partner als dat nodig is.</span></li><li><b>Functies op maat</b><span>Van contactformulier tot reservering of klantomgeving.</span></li></ul><p className="service-fit">Van een onepager tot een uitgebreid platform. Je ontvangt vooraf een voorstel met de pagina’s, functies en prijs. Alle websitepakketten krijgen een eigen ontwerp.</p><p className="service-context-link">Nog geen duidelijke richting? <a href="/tools/website-ontwerp-tool">Maak eerst je eigen websitevoorbeeld</a>.</p><a className="button" href="/diensten/webdesign">Bekijk de mogelijkheden voor je website<Arrow/></a></div><WorkPair/></div></section>
  <section className="overview-reach" id="seo"><div className="wrap overview-reach-grid"><div className="overview-topic-copy"><Eyebrow>02 / Beter gevonden worden</Eyebrow><h2>Je aanbod is er.<br/><em>Nu nog gevonden worden.</em></h2><p>Je website staat online, maar de juiste bezoekers vinden je nog niet. Ik onderzoek de technische basis, de vragen van je klanten en de pagina’s die daarop antwoord geven. Daaruit volgt een gerichte verbeterlijst, een eenmalige opdracht of doorlopende begeleiding.</p><p className="service-context-link">Zelf zien waar de techniek hapert? <a href="/tools/seo-audit">Start de gratis SEO-audit</a>.</p><a className="button" href="/diensten/seo">Bekijk de aanpak voor vindbaarheid<Arrow/></a></div><div className="overview-reach-topics"><article data-reveal><span>01</span><div><h3>Gevonden worden.</h3><p>Zoekvragen, dienstenpagina’s, lokale vindbaarheid en een goede technische basis.</p></div></article><article data-reveal><span>02</span><div><h3>Iets te vertellen hebben.</h3><p>Dienstenpagina’s die vragen beantwoorden en blogs vanuit jouw expertise.</p></div></article><article data-reveal><span>03</span><div><h3>Herkenbaar blijven.</h3><p>Dezelfde basisinhoud, passend gemaakt voor Instagram, Facebook en LinkedIn.</p></div></article><div className="overview-reading-route" aria-label="De route van je bezoeker"><span>Zoeken</span><Arrow/><span>Lezen</span><Arrow/><b>Contact</b></div></div></div></section>
  <section className="overview-automation" id="ai-automatisering"><div className="wrap overview-automation-grid"><div className="overview-topic-copy"><Eyebrow>03 / Minder terugkerend handwerk</Eyebrow><h2>Steeds dezelfde taak?<br/><em>Laat je systemen helpen.</em></h2><p>Neem je aanvragen over uit e-mails, voer je gegevens dubbel in of beantwoord je steeds dezelfde vragen? We brengen eerst de taak en uitzonderingen in kaart. Daarna bouw ik een formulier, rekentool of koppeling die past bij je werkwijze.</p><ul className="overview-tool-topics"><li>Rekentools & calculators</li><li>Contact- en aanvraagformulieren</li><li>AI-assistenten & documentverwerking</li><li>Backend, API’s & softwarekoppelingen</li></ul><p className="service-fit">Vaste regels waar dat kan, AI waar interpretatie nodig is. Je houdt afgesproken controlemomenten; beschikbare toegang tot je software bepaalt wat gekoppeld kan worden.</p><p className="service-context-link">Begin met een taak: <a href="/tools/automatiseringsplan">maak je automatiseringsplan</a>.</p><a className="button" href="/diensten/ai-automatisering">Ontdek tools & automatisering<Arrow/></a></div><div className="overview-flow" data-scroll-scene="unfold"><div className="overview-flow-heading"><span>Een voorbeeld van wat mogelijk is</span><strong>Van aanvraag.<br/><em>Naar een volgende stap.</em></strong></div><ol data-scene-target>{[["Je klant vult in","Een duidelijk formulier vraagt wat je nodig hebt."],["De informatie krijgt een plek","Gegevens worden gecontroleerd en aan je software gekoppeld."],["Jij kunt verder","Een dossier, taak of conceptantwoord staat klaar voor je controle."]].map(([title,text],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></div></section>
  <section className="overview-apps" id="apps"><div className="wrap overview-design-grid"><div className="overview-topic-copy"><Eyebrow>04 / Een eigen digitale toepassing</Eyebrow><h2>Laat klanten iets regelen.<br/><em>Op hun eigen moment.</em></h2><p>Afspraken beheren, de status van een aanvraag volgen of gegevens delen met je team. Ik ontwerp en bouw de schermen en functies die daarvoor nodig zijn. We kiezen samen of een webapp in de browser voldoende is, of dat een app voor iPhone en Android beter past.</p><ul className="overview-scope"><li><b>Apps voor iPhone & Android</b><span>Een eigen toepassing op de telefoon van je klant of medewerker.</span></li><li><b>Webapps & klantportalen</b><span>Inloggen, gegevens delen en samenwerken via de browser.</span></li><li><b>Van ontwerp tot publicatie</b><span>Schermen, functies, testen en de afgesproken stappen naar de appwinkels.</span></li></ul><a className="button" href="/diensten/apps">Ontdek apps voor iPhone & Android<Arrow/></a><a className="text-link" href="/diensten/webapps">Of bekijk webapps & klantportalen<Arrow/></a></div><ServiceCanvas kind="apps" animated/></div></section>
  <section className="wrap services-tools-gateway"><div><Eyebrow>Eerst zelf ontdekken / Gratis tools</Eyebrow><h2>Van een vraag.<br/><em>Naar een duidelijker plan.</em></h2><p>Waar loopt je website vast? Welk ontwerp past bij je bedrijf? En wat mag een nieuwe website kosten? Onze tools geven je een concreet vertrekpunt, voordat je een dienst kiest.</p><a className="button" href="/tools">Ontdek alle tools & checks<Arrow/></a></div><ol aria-label="Wat je met de tools kunt doen"><li><span>01</span><div><b>Bekijk wat beter kan</b><p>Onderzoek je website en technische SEO.</p></div></li><li><span>02</span><div><b>Maak je wensen zichtbaar</b><p>Verken een ontwerp, websiteplan of automatisering.</p></div></li><li><span>03</span><div><b>Kies je volgende stap</b><p>Neem je uitkomst mee als je hulp wilt bij de uitvoering.</p></div></li></ol></section>
  <section className="overview-care-chapter" id="onderhoud"><div className="wrap overview-care-grid"><div className="overview-topic-copy"><Eyebrow>05 / Ook na de lancering</Eyebrow><h2>Je website blijft draaien.<br/><em>Jij houdt overzicht.</em></h2><p>Na de lancering kun je techniek en nieuwe inhoud laten verzorgen. Bij een nieuwe website hoort hosting met een eerste looptijd van twaalf maanden. Technisch onderhoud, SEO-werk en content kies je afzonderlijk; de pakketten maken duidelijk wat erbij hoort.</p><ul className="overview-scope"><li><b>Online & technisch verzorgd</b><span>Hosting, maandelijkse controles en herstel van technische fouten.</span></li><li><b>Je bestaande website bijhouden</b><span>Doorlopende SEO-verbeteringen aan teksten en code.</span></li><li><b>Nieuwe inhoud op een vast ritme</b><span>Blogs en berichten voor Instagram, Facebook of LinkedIn.</span></li></ul><a className="button" href="/diensten/onderhoud-hosting">Onderhoud, hosting & maandpakketten<Arrow/></a><div className="care-services-links"><a className="text-link" href="/diensten/content#maandpakketten">Blogs laten verzorgen<Arrow/></a><a className="text-link" href="/diensten/social-media#maandpakketten">Social media uitbesteden<Arrow/></a></div></div><ServiceCanvas kind="onderhoud-hosting" animated/></div></section>
  <section className="wrap hub-discovery"><div><Eyebrow>Sitesnit Hub / Na de lancering</Eyebrow><h2>Je website is live.<br/><em>Wat levert het bezoek je op?</em></h2><p>Waar komen bezoekers vandaan? Welke pagina’s trekken aandacht? En wat is er deze maand aan je website gedaan? In Sitesnit Hub vind je beschikbare cijfers en werkzaamheden bij elkaar, zonder losse rapporten bij elkaar te zoeken.</p><a className="button" href="/diensten/website-monitoring">Zo werkt jouw klantomgeving<Arrow/></a><p className="small">Een aanvullende klantdienst met vooraf afgesproken koppelingen en maandbedrag. Verbeterwerk spreken we apart af.</p></div><div className="hub-discovery-visual"><span>Je eigen websiteoverzicht</span><ol><li><b>Bezoekers</b><span>Herkomst · dagen · maanden vergelijken</span></li><li><b>Google</b><span>Zoekvragen · vertoningen · klikken</span></li><li><b>Werk & bereikbaarheid</b><span>Wat is gemeten, gedaan en gepland?</span></li></ol><a href="/hub/demo/sitesnit">Bekijk de Hub met voorbeeldgegevens<Arrow/></a><small>Demonstratie; geen echte bezoekerscijfers.</small></div></section>
  <section className="wrap services-closing-note"><span>Waar wil jij mee verder?</span><strong>We maken het concreet.</strong><p>Je hoeft nog geen dienst of pakket te kiezen. Vertel wat je wilt bereiken; dan kijken we welke onderdelen daarbij passen.</p><a className="button" href="/contact">Bespreek je plannen<Arrow/></a></section>
</div>;}
