import type { Service } from "./service-data";

export const specialistServices: Service[] = [
  {
    slug:"seo-optimalisatie",anchor:"seo-optimalisatie",name:"SEO-optimalisatie",number:"01",tone:"green",group:"SEO & content",
    title:"Een echte zoekvraag.",accent:"Een passend antwoord.",
    summary:"Je wilt gevonden worden door mensen die zoeken naar wat jouw bedrijf doet. Daarvoor moeten inhoud, paginastructuur en techniek elkaar ondersteunen. We onderzoeken relevante zoekvragen en verbeteren de afgesproken pagina’s. Voor ondernemers in Venlo en Limburg nemen we het echte werkgebied mee.",
    tags:["Zoekintentie","Technische SEO","Lokale vindbaarheid"],introTitle:"Van zoekvraag",introAccent:"naar een duidelijke route.",
    intro:"SEO begint met weten welke informatie je klant nodig heeft. We brengen je aanbod, bestaande pagina’s en beschikbare zoekgegevens bij elkaar. Daaruit volgt een concrete lijst van inhoudelijke en technische verbeteringen, met een duidelijke prioriteit.",
    methods:[
      ["Welke vraag hoort op welke pagina?","We beginnen met je diensten, klanten en bestaande website. Welke vragen stellen mensen voordat ze contact opnemen? Welke informatie helpt hen kiezen? We brengen onderwerpen bij elkaar en bepalen welke pagina iedere vraag beantwoordt. Goede bestaande inhoud blijft bruikbaar. Waar uitleg ontbreekt, spreken we af wat wordt aangevuld. Zo krijgen diensten, praktische artikelen en voorbeelden elk een eigen rol."],
      ["Van losse tekst naar een duidelijke route","Een pagina moet meer doen dan een zoekterm noemen. We werken titels, koppen en teksten uit rond de vraag van de bezoeker. Voorbeelden geven context; interne links leiden naar relevante verdieping of contact. Jouw kennis vormt de inhoudelijke basis. We spreken af wie informatie aanlevert en controleert, zodat de tekst past bij wat je bedrijf werkelijk aanbiedt en uitvoert."],
      ["De techniek achter bereikbare inhoud","We controleren of zoekmachines belangrijke pagina’s kunnen bereiken en hoe de website haar inhoud aanbiedt. Daarbij bekijken we links, URL’s, indexeerbaarheid, mobiele bruikbaarheid en laadtijd. Technische bevindingen vertalen we naar concrete verbeteringen: een ontbrekende pagina herstellen, een verkeerde verwijzing aanpassen of inhoud beter bereikbaar maken. Daarna voeren we de afgesproken aanpassingen uit en controleren we de werking."],
      ["Lokale relevantie en een passend vervolg","Voor een ondernemer in Venlo of Limburg moeten diensten en werkgebied herkenbaar zijn. We gebruiken je daadwerkelijke werkzaamheden, contactgegevens en beschikbare voorbeelden. Een bestaand Google Bedrijfsprofiel en zoekgegevens nemen we mee wanneer ze beschikbaar zijn. Na aanpassingen beoordelen we welke informatie verdere aandacht vraagt. Nieuwe blogs en doorlopende verbetering kun je als vervolg afspreken."]
    ],optionsTitle:"Verder bouwen",optionsAccent:"op een goede basis.",options:[],
    faqs:[
      ["Kunnen jullie mijn huidige website verbeteren?","We bekijken eerst hoe je website is opgebouwd en welke toegang beschikbaar is. Daarna bepalen we welke inhoudelijke en technische aanpassingen mogelijk zijn. Een volledige nieuwe website is daarvoor niet altijd nodig."],
      ["Wanneer zie ik verschil in Google?","Dat verschilt per website, onderwerp en concurrentie. Zoekmachines bepalen wanneer veranderingen worden verwerkt. We spreken af welk werk wordt uitgevoerd en gebruiken beschikbare gegevens om het vervolg te beoordelen. Een positie of termijn kunnen we niet garanderen."],
      ["Wat is het verschil met blogs en onderhoud?","SEO-optimalisatie richt zich op afgesproken inhoudelijke en technische verbeteringen. Blogpakketten leveren nieuwe artikelen. Het onderhoudspakket met SEO omvat doorlopende aanpassingen aan bestaande teksten en code. We maken duidelijk welke werkzaamheden je kiest."]
    ],cta:"Bespreek je SEO",contact:"/contact?dienst=seo-optimalisatie",meta:"Laat je bestaande website verbeteren voor Google en je bezoekers. Sitesnit onderzoekt zoekvragen, teksten, interne links, techniek en lokale vindbaarheid."
  },
  {
    slug:"formulieren-rekentools",anchor:"formulieren-rekentools",name:"Formulieren & rekentools",number:"02",tone:"blue",group:"Tools & automatisering",
    title:"De juiste vragen.",accent:"Een bruikbare uitkomst.",
    summary:"Een formulier helpt bezoekers hun vraag door te geven. Een rekentool maakt gegevens begrijpelijk. We ontwerpen contactformulieren, intakes, offerteaanvragen en calculators rond de informatie die je werkelijk nodig hebt. Van de eerste vraag tot de bevestiging of berekening krijgt iedere stap een duidelijke taak.",
    tags:["Contact & intake","Offerteaanvragen","Calculators"],introTitle:"Prettig voor je bezoeker.",introAccent:"Bruikbaar voor je bedrijf.",
    intro:"We leggen vooraf vast wat je vraagt, hoe gegevens worden gecontroleerd en waar ze terechtkomen. Een aanvraag krijgt een logische opvolging; een berekening heeft uitlegbare regels. Zo bouwen we een hulpmiddel dat onderdeel wordt van je dagelijkse werk.",
    methods:[
      ["Vragen die passen bij de aanvraag","Welke informatie heb je nodig om een aanvraag goed te behandelen? Een kort contactformulier vraagt iets anders dan een uitgebreide intake of offerteaanvraag. Vragen krijgen een begrijpelijke volgorde en, waar passend, meerdere stappen. Verplichte velden en invoerregels worden uitgelegd. Zo weten bezoekers wat ze moeten invullen en ontvangen medewerkers de afgesproken gegevens om verder te werken."],
      ["Een berekening die je kunt uitleggen","Voor een calculator leggen we de invoer, rekenregels en gewenste uitkomst vast. Welke eenheden gebruik je, welke aannames gelden en hoe worden bedragen afgerond? We vertalen die regels naar duidelijke velden en een passende weergave van het resultaat. Met afgesproken voorbeelden controleren we de berekening. De bezoeker ziet wat is ingevoerd en hoe de uitkomst moet worden gelezen."],
      ["Na verzenden moet het verdergaan","Een formulier is pas bruikbaar wanneer duidelijk is wat er na de aanvraag gebeurt. We leggen vast waar gegevens worden opgeslagen of doorgegeven en welke bevestiging de bezoeker ontvangt. Een koppeling met bestaande software kan daarbij horen als die technisch mogelijk is. Ook ontbrekende informatie en mislukte verwerking krijgen aandacht. Zo heeft iedere aanvraag een afgesproken bestemming en een route voor opvolging."],
      ["Prettig invullen op ieder scherm","We werken de bediening eerst voor mobiel uit: leesbare vragen, passende velden, herkenbare knoppen en begrijpelijke foutmeldingen. Daarna controleren we grotere schermen en toetsenbordbediening. Bij meerdere stappen bekijken we hoe bezoekers teruggaan en invoer aanpassen. We testen ook onvolledige of ongeldige invoer. Jij krijgt uitleg over de werking; latere wijzigingen worden opnieuw afgestemd en getest."]
    ],optionsTitle:"Van invoer",optionsAccent:"naar opvolging.",options:[],
    faqs:[
      ["Maakt een formulier mijn website automatisch maatwerk?","Een standaardcontactformulier is op zichzelf geen reden voor een maatwerkpakket. Meerdere stappen, bijzondere berekeningen of softwarekoppelingen kunnen extra uitwerking vragen. We bepalen de benodigde werking voordat we de omvang en investering afspreken."],
      ["Heeft een rekentool altijd AI nodig?","Berekeningen kunnen met vaste, testbare regels worden uitgevoerd. AI is daarvoor niet automatisch nodig. Gegevens uitrekenen vraagt iets anders dan een document samenvatten of vrije tekst interpreteren. We kiezen de techniek op basis van de taak."],
      ["Kan een aanvraag naar mijn bestaande software?","Dat onderzoeken we aan de hand van de mogelijkheden en toegangsrechten van die software. We spreken af welke gegevens worden doorgegeven en wat er gebeurt wanneer informatie ontbreekt of een koppeling niet beschikbaar is."]
    ],cta:"Bespreek je formulier of tool",contact:"/contact?dienst=formulieren-rekentools",meta:"Laat een intake, offerteformulier of calculator bouwen. Van begrijpelijke vragen en geteste berekeningen tot het doorgeven en opvolgen van een aanvraag."
  },
  {
    slug:"ai-koppelingen",anchor:"ai-koppelingen",name:"AI & softwarekoppelingen",number:"03",tone:"peach",group:"Tools & automatisering",
    title:"Minder handelingen.",accent:"Meer overzicht.",
    summary:"Gegevens overtypen, documenten nalopen of dezelfde vragen beantwoorden kost aandacht. We onderzoeken welke stappen software kan voorbereiden en waar jouw controle nodig blijft. Met een AI-assistent, documentverwerking of koppeling tussen bestaande systemen. We beginnen bij één concreet proces in jouw bedrijf.",
    tags:["AI-assistenten","Documentverwerking","API & backend"],introTitle:"Begin met de taak.",introAccent:"Bouw wat je helpt.",
    intro:"Een bruikbare automatisering past bij de mensen en systemen die ermee werken. We leggen invoer, toegang, verwerking en controle vast voordat we bouwen. Zo weet je welke handelingen worden overgenomen, welke uitzonderingen aandacht vragen en wie het resultaat gebruikt.",
    methods:[
      ["Eerst begrijpen hoe het werk loopt","We volgen een terugkerende taak van begin tot eind. Waar komt informatie binnen, wie verwerkt die en welke software wordt gebruikt? Samen benoemen we uitzonderingen en beslissingen waarvoor ervaring nodig is. Daaruit volgt welke stap kan worden vereenvoudigd en welke controle bij een medewerker blijft. De opdracht krijgt een afgebakend proces met duidelijke afspraken over wat de oplossing moet doen."],
      ["AI gebruiken voor taal en documenten","Een AI-assistent kan informatie uit documenten ordenen, een conceptantwoord voorbereiden of vragen beantwoorden met behulp van bedrijfsinformatie. We bepalen welke bronnen gebruikt mogen worden en welke gegevens nodig zijn. De toepassing krijgt instructies voor de afgesproken taak en een route voor vragen die extra aandacht vragen. Concepten en belangrijke toezeggingen worden gecontroleerd op de momenten die we samen afspreken."],
      ["Software met elkaar laten samenwerken","Een koppeling kan aanvraaggegevens, klantinformatie of orderstatus doorgeven aan een ander systeem. We onderzoeken beschikbare API’s, exports en toegangsrechten en bepalen welke gegevens leidend zijn. Daarna leggen we de vertaling tussen velden en de verwerkingsregels vast. Controles tegen dubbele verwerking en herkenbare foutmeldingen helpen medewerkers zien wanneer opvolging nodig is. Zo wordt een backend een bruikbare verbinding tussen je dagelijkse werkzaamheden."],
      ["Controle houden na de ingebruikname","We testen de afgesproken stappen met passende voorbeelden, inclusief ontbrekende informatie en uitzonderingen. Jij beoordeelt of de uitkomst bruikbaar is in het dagelijkse werk. We maken duidelijk welke handelingen zelfstandig verlopen en waar iemand moet controleren. Ook toegang, eventuele gebruikskosten en onderhoud worden besproken. Je weet hoe je de oplossing gebruikt en welke veranderingen later een aanvullende afspraak nodig hebben."]
    ],optionsTitle:"Samenwerkende systemen.",optionsAccent:"Duidelijke afspraken.",options:[],
    faqs:[
      ["Moet ik andere software gaan gebruiken?","We beginnen bij de systemen die je al gebruikt. De beschikbare koppelmogelijkheden, gegevens en toegangsrechten bepalen wat mogelijk is. Wanneer een andere oplossing nodig lijkt, bespreken we dat voordat we de opdracht vastleggen."],
      ["Verstuurt AI zelfstandig antwoorden of facturen?","Dat hangt af van de afgesproken werking. Een antwoord of factuur kan als concept worden voorbereid, waarna een medewerker controleert en verstuurt. We bepalen vooraf welke handelingen zelfstandig mogen verlopen en waar jouw goedkeuring nodig blijft."],
      ["Kan dit later worden uitgebreid?","We bespreken hoe het proces kan meegroeien met je bedrijf. Nieuwe systemen, andere gegevens of extra beslisregels kunnen aanpassingen vragen. We beoordelen de gevolgen voor verwerking, controles en gebruikskosten voordat we uitbreiden."]
    ],cta:"Bespreek je proces",contact:"/contact?dienst=ai-koppelingen",meta:"Laat een AI-chatbot, documentverwerking of softwarekoppeling uitwerken. Bekijk hoe bronnen, gegevens en menselijke controle onderdeel worden van de oplossing."
  }
];
