/* eslint-disable */
// Generated by Wrangler by running `wrangler types workers/hub-sync/worker-configuration.d.ts --config workers/hub-sync/wrangler.jsonc --env-file workers/hub-sync/.dev.vars.example --env-interface HubSyncWorkerEnv --strict-vars=false --include-runtime=false` (hash: c5a14787fd44967815edd8714fff5941)
interface __BaseEnv_HubSyncWorkerEnv {
	HUB_SYNC_ENABLED: string;
	HUB_SYNC_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_HubSyncWorkerEnv {}
}
interface HubSyncWorkerEnv extends __BaseEnv_HubSyncWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "HUB_SYNC_ENABLED" | "HUB_SYNC_SECRET">> {}
}
