export type CheckState='passed'|'failed'|'review'|'not-applicable'|'not-tested';
export type DetailedCheck={id:string;title:string;category:string;source:'HTML'|'Lighthouse';state:CheckState;weight:number;evidence:string;action:string;snippet?:string};
// Stable IDs represent different questions, not one question counted once per URL.
export const htmlCatalog=[
 ['http','HTTP-respons','Bereikbaarheid',3],
 ['html','HTML-document ontvangen','Bereikbaarheid',2],
 ['noindex','Indexeringsinstructies','Indexering',3],
 ['canonical-count','Tegenstrijdige canonicals','Indexering',2],
 ['canonical-url','Canonical-adres geldig','Indexering',2],
 ['canonical-target','Canonicalbestemming in de steekproef','Indexering',2],
 ['canonical-index','Indexeringsinstructies van canonicalbestemming','Indexering',2],
 ['refresh','Automatische meta-refresh','Indexering',1],
 ['title','Paginatitel aanwezig','Inhoud',2],
 ['title-count','Meerdere title-elementen','Inhoud',1],
 ['title-unique','Unieke titel binnen de crawl','Inhoud',2],
 ['description','Metabeschrijving aanwezig','Inhoud',1],
 ['description-count','Meerdere metabeschrijvingen','Inhoud',1],
 ['description-unique','Unieke beschrijving binnen de crawl','Inhoud',1],
 ['title-length','Lengte van de paginatitel','Inhoud',0],
 ['description-length','Lengte van de metabeschrijving','Inhoud',0],
 ['body-text','Leesbare tekst in ontvangen HTML','Inhoud',1],
 ['h1','Niet-lege hoofdkop','Koppen',2],
 ['h1-count','Aantal hoofdkoppen','Koppen',0],
 ['heading-empty','Lege koppen','Koppen',1],
 ['heading-order','Overgeslagen kopniveaus','Koppen',0],
 ['h1-title','Verhouding titel en hoofdkop','Koppen',0],
 ['main','Hoofdinhoud gemarkeerd','Koppen',0],
 ['link-name','Lege linkteksten in HTML','Links',1],
 ['link-placeholder','Links met een lege bestemming','Links',0],
 ['link-http','Onbeveiligde interne verwijzingen','Links',1],
 ['link-broken','Interne links naar gemeten foutpagina’s','Links',3],
 ['link-redirect','Interne links naar gemeten redirects','Links',0],
 ['link-fragment','Verwijzingen naar ontbrekende lokale ankers','Links',0],
 ['alt','Alt-attributen bij afbeeldingen','Beelden',1],
 ['image-src','Afbeeldingen met bronadres','Beelden',1],
 ['image-dimensions','Gereserveerde afbeeldingsafmetingen','Beelden',0],
 ['image-http','Onbeveiligde afbeeldingsbronnen','Beelden',2],
 ['image-srcset','Responsieve afbeeldingsvarianten','Beelden',0],
 ['image-priority','Tegenstrijdige laadprioriteit bij beelden','Beelden',1],
 ['image-alt-file','Bestandsnamen als alt-tekst','Beelden',0],
 ['og-title','Open Graph-titel','Delen',1],
 ['og-description','Open Graph-beschrijving','Delen',1],
 ['og-image','Open Graph-afbeeldingsadres','Delen',1],
 ['og-url','Open Graph-pagina-adres','Delen',1],
 ['og-type','Open Graph-inhoudstype','Delen',1],
 ['twitter-card','Twitter/X-kaarttype','Delen',1],
 ['twitter-title','Twitter/X-titel of OG-fallback','Delen',1],
 ['twitter-image','Twitter/X-beeld of OG-fallback','Delen',1],
 ['json-present','Gestructureerde data aanwezig','Gestructureerde data',0],
 ['json','JSON-LD leesbaar','Gestructureerde data',2],
 ['json-context','Schema.org-context','Gestructureerde data',1],
 ['json-type','Type in gestructureerde data','Gestructureerde data',1],
 ['json-url','Adressen in gestructureerde data','Gestructureerde data',1],
 ['breadcrumbs','Volgorde in BreadcrumbList','Gestructureerde data',1],
 ['lang','Documenttaal ingevuld','Taal & mobiel',1],
 ['hreflang-url','Adressen van taalvarianten','Taal & mobiel',1],
 ['hreflang-self','Eigen taalvariant vermeld','Taal & mobiel',0],
 ['viewport','Mobiele viewport ingesteld','Taal & mobiel',2],
 ['zoom','Zoomen niet door metadata beperkt','Taal & mobiel',1],
 ['charset','Tekencodering gedeclareerd','Server & veiligheid',1],
 ['nosniff','Content-Type-sniffing beperkt','Server & veiligheid',0],
 ['hsts','HTTPS-beleid via HSTS','Server & veiligheid',0],
 ['csp','Content Security Policy aanwezig','Server & veiligheid',0],
 ['referrer','Referrerbeleid opgegeven','Server & veiligheid',0],
] as const;
export const lighthouseCatalog=[
 ['first-contentful-paint','Eerste zichtbare inhoud','Prestaties'],
 ['largest-contentful-paint','Grootste zichtbare element','Prestaties'],
 ['total-blocking-time','Blokkering van de hoofdthread','Prestaties'],
 ['cumulative-layout-shift','Gemeten verspringingen','Prestaties'],
 ['speed-index','Visuele opbouwsnelheid','Prestaties'],
 ['unused-javascript','Ongebruikte JavaScript','Prestaties'],
 ['unused-css-rules','Ongebruikte CSS','Prestaties'],
 ['render-blocking-insight','Renderblokkerende bestanden','Prestaties'],
 ['image-delivery-insight','Efficiënte beeldlevering','Prestaties'],
 ['cache-insight','Cachebeleid voor bestanden','Prestaties'],
 ['document-latency-insight','Documentvertraging','Prestaties'],
 ['lcp-discovery-insight','Ontdekking van het LCP-element','Prestaties'],
 ['cls-culprits-insight','Oorzaken van verschuivingen','Prestaties'],
 ['font-display-insight','Weergave tijdens lettertypeladen','Prestaties'],
 ['forced-reflow-insight','Gedwongen layoutberekeningen','Prestaties'],
 ['network-dependency-tree-insight','Afhankelijke netwerkaanvragen','Prestaties'],
 ['legacy-javascript-insight','Verouderde JavaScript voor moderne browsers','Prestaties'],
 ['dom-size-insight','Omvang van het gerenderde document','Prestaties'],
 ['color-contrast','Gemeten tekstcontrast','Toegankelijkheid'],
 ['button-name','Toegankelijke knopnamen','Toegankelijkheid'],
 ['label','Labels van invoervelden','Toegankelijkheid'],
 ['aria-allowed-attr','Toegestane ARIA-attributen','Toegankelijkheid'],
 ['aria-valid-attr','Bestaande ARIA-attribuutnamen','Toegankelijkheid'],
 ['aria-valid-attr-value','Geldige ARIA-waarden','Toegankelijkheid'],
 ['aria-required-attr','Vereiste ARIA-attributen','Toegankelijkheid'],
 ['aria-required-children','Vereiste onderliggende ARIA-elementen','Toegankelijkheid'],
 ['aria-required-parent','Vereiste bovenliggende ARIA-elementen','Toegankelijkheid'],
 ['aria-roles','Geldige ARIA-rollen','Toegankelijkheid'],
 ['aria-hidden-focus','Focus binnen verborgen ARIA-inhoud','Toegankelijkheid'],
 ['select-name','Namen van keuzelijsten','Toegankelijkheid'],
 ['frame-title','Titels van ingesloten frames','Toegankelijkheid'],
 ['list','Semantiek van lijsten','Toegankelijkheid'],
 ['listitem','Lijstitems binnen een lijst','Toegankelijkheid'],
 ['td-headers-attr','Verwijzingen tussen tabelcellen en koppen','Toegankelijkheid'],
 ['th-has-data-cells','Tabelkoppen bij gegevenscellen','Toegankelijkheid'],
 ['valid-lang','Geldige documenttaal','Toegankelijkheid'],
 ['errors-in-console','Browserconsolefouten','Browserkwaliteit'],
 ['is-on-https','Onveilige geladen bronnen','Browserkwaliteit'],
 ['deprecations','Verouderde browser-API’s','Browserkwaliteit'],
 ['inspector-issues','Problemen gemeld door browserinspectie','Browserkwaliteit'],
] as const;
export const CHECK_COUNT=htmlCatalog.length+lighthouseCatalog.length;
