export type AuditEditorial = {
  label: string; answer: string; example: { title: string; before: string; decision: string; after: string };
  steps: string[]; pitfalls: string; faqs: {question:string; answer:string; href?:string; link?:string}[];
  next: string[]; source: {label:string; href:string};
};
export const auditEditorial: Record<string, AuditEditorial> = {
  'indexering-controleren': {
    label: 'Mag deze pagina gevonden worden?',
    answer: 'Controleer eerst of de publieke pagina bereikbaar is en geen onbedoelde noindex bevat. Kijk daarna in Google Search Console of Google de pagina daadwerkelijk heeft opgenomen. Een crawl kan blokkades aanwijzen; hij bevestigt geen opname in Google.',
    example: {title:'Een dienstenpagina blijft buiten Google',before:'De nieuwe dienstenpagina opent normaal, maar de HTML bevat nog noindex. Die instelling is tijdens het bouwen gebruikt.',decision:'Deze pagina legt een echte dienst uit en hoort publiek vindbaar te zijn. De klantomgeving hoort dat juist niet.',after:'Verwijder de blokkade alleen op de publieke pagina’s. Controleer de nieuwe response en vraag daarna via URL-inspectie een herbeoordeling aan.'},
    steps:['Maak een lijst van pagina’s die zelfstandig in Google mogen verschijnen. Scheid die van accounts, persoonlijke rapporten en testomgevingen.','Bekijk de gepubliceerde URL zonder ingelogd beheerdersaccount. Controleer HTTP-status, HTML-robots en X-Robots-Tag; een instelling in het CMS alleen is geen bewijs.','Controleer de gekozen canonical. Een bereikbare pagina kan alsnog naar een andere hoofdversie verwijzen.','Controleer na publicatie opnieuw en leg de uitkomst naast URL-inspectie. De live test en de laatst door Google opgeslagen versie kunnen verschillen.'],
    pitfalls:'Robots.txt blokkeren is geen vervanging voor noindex. Als Google de pagina niet mag lezen, kan het de noindex daarop ook niet ontdekken. Voor vertrouwelijke informatie gebruik je toegangsbeveiliging. Verwijder verder niet alle blokkades tegelijk: een oplossing voor de homepage kan anders je account- of testpagina’s openbaar vindbaar maken.',
    faqs:[{question:'Betekent HTTP 200 dat mijn pagina in Google staat?',answer:'Nee. Het betekent dat de server een succesvolle response teruggeeft. Google moet de pagina nog ontdekken, verwerken en selecteren. Een 200-pagina kan bovendien een noindex of een verwijzing naar een andere hoofdversie bevatten.'},{question:'Hoe snel verschijnt een herstelde pagina in Google?',answer:'Daar is geen vaste termijn voor. Een nieuwe crawl aanvragen is geen garantie op opname. Controleer eerst dat de blokkade werkelijk verdwenen is en dat de pagina unieke, bruikbare inhoud heeft.',href:'/website-niet-gevonden-google',link:'Lees het verschil tussen indexering en vindbaarheid'},{question:'Moet mijn hele website indexeerbaar zijn?',answer:'Alleen pagina’s die bedoeld zijn voor zoekresultaten. Een login, persoonlijk klantdossier of privérapport vraagt een andere behandeling dan een dienstenpagina.'}],
    next:['canonical-controleren','rapport-naar-actie'],source:{label:'Google: indexering blokkeren met noindex',href:'https://developers.google.com/search/docs/crawling-indexing/block-indexing'}
  },
  'interne-links-controleren': {
    label:'Van klik naar de juiste bestemming',
    answer:'Controleer zowel de bestemming als de pagina waarop een interne link staat. Herstel een verdwenen pagina als die nog nodig is, werk verplaatste links direct bij en gebruik alleen een redirect naar inhoud die dezelfde vraag beantwoordt.',
    example:{title:'Een aanvraagknop wijst naar een oud adres',before:'Op de dienstenpagina verwijst “Vraag een voorstel aan” naar /offerte-oud. Die URL geeft 404 terug.',decision:'Het aanvraagformulier bestaat nog, maar staat nu op /contact. De bezoeker moet dezelfde taak kunnen uitvoeren.',after:'Pas de knop direct aan naar /contact. Gebruik een permanente redirect vanaf het oude adres als er ook oude bookmarks of externe verwijzingen bestaan.'},
    steps:['Begin bij routes die iemand nodig heeft om een keuze te maken: dienst, project, kosten en contact.','Noteer bron-URL, zichtbare linktekst, bestemming en statuscode. Zo kan degene die de site beheert de verwijzing terugvinden.','Controleer of de pagina verplaatst, verkeerd gespeld of bewust verwijderd is. Een 404 is een status, nog geen diagnose.','Werk de bronlink bij en test het nieuwe eindadres. Controleer een eventuele redirect zonder tussenstappen en doorloop de route ook op mobiel.'],
    pitfalls:'Een redirect lost een verkeerde belofte niet op. Een link met “Prijzen” moet op prijzen uitkomen, ook als een andere bestemming technisch 200 teruggeeft. Vermijd bovendien een keten van oude adressen: laat oude verwijzingen zo direct mogelijk naar de juiste huidige pagina gaan. Het aantal links op zichzelf vertelt niets over hun bruikbaarheid.',
    faqs:[{question:'Hoeveel interne links mag een pagina hebben?',answer:'Er is geen ideaal aantal. Link waar een volgende uitleg of actie nuttig is en gebruik een herkenbare linktekst. Een navigatieoverzicht mag meer links bevatten dan een kort antwoordartikel.'},{question:'Moet ik iedere 404 doorsturen?',answer:'Nee. Als de inhoud bewust weg is en er geen passend alternatief bestaat, kan 404 of 410 correct zijn. Verwijder dan wel verwijzingen die bezoekers er nog onnodig naartoe sturen.',href:'/404-fouten-oplossen',link:'Kies de juiste oplossing per 404'},{question:'Vindt de audit alle kapotte links?',answer:'Nee. De gratis audit onderzoekt maximaal twintig URL’s binnen zijn crawlregels. Hij kan dus geen volledigheid claimen voor grotere websites, bestanden of links die pas na JavaScript verschijnen.'}],
    next:['rapport-naar-actie','indexering-controleren'],source:{label:'Google: interne links en linkteksten',href:'https://developers.google.com/search/docs/crawling-indexing/links-crawlable'}
  },
  'canonical-controleren': {
    label:'Eén inhoud, een duidelijke hoofdversie',
    answer:'Een canonical vertelt zoekmachines welke URL je als hoofdversie van gelijke of sterk vergelijkbare inhoud verkiest. Controleer of die bestemming klopt en bereikbaar is, en of interne links en sitemap dezelfde keuze ondersteunen. Google kan een andere versie kiezen.',
    example:{title:'De site gebruikt www, de canonical niet',before:'Bezoekers landen op https://www.voorbeeld.nl/diensten. De canonical noemt https://voorbeeld.nl/diensten, dat weer naar www doorstuurt.',decision:'De publieke hoofdversie is www. Het verschil komt uit een oude domeininstelling, niet uit een inhoudelijke keuze.',after:'Werk de centrale domeininstelling bij. Controleer daarna canonical, sitemap en interne links op de uiteindelijke www-URL; behoud passende redirects voor oude adressen.'},
    steps:['Bepaal welke URL de hoofdversie hoort te zijn en waarom. Vergelijk de inhoud, niet alleen de spelling van de adressen.','Open de canonicalbestemming en controleer dat die geen foutpagina, geblokkeerde route of omweg is.','Zoek naar dubbele uitvoer door thema, plugin of template. Kies één bron die de metadata beheert.','Controleer na herstel enkele verschillende paginatypes. Gebruik Search Console om jouw voorkeur te vergelijken met Googles gekozen versie.'],
    pitfalls:'Een canonical is geen redirect voor bezoekers en geen middel om totaal verschillende diensten samen te voegen. Zet niet iedere pagina naar de homepage: dan geef je een onlogische voorkeursversie door. Een ontbrekende canonical betekent ook niet automatisch dat Google geen hoofdversie kan bepalen; beoordeel vooral situaties met echte URL-varianten of tegenstrijdige signalen.',
    faqs:[{question:'Is www beter voor SEO dan zonder www?',answer:'Geen van beide is op zichzelf de betere keuze. Gebruik één consistente hoofdversie en laat relevante oude varianten daarheen verwijzen.'},{question:'Wat is het verschil tussen een redirect en canonical?',answer:'Een redirect stuurt de bezoeker naar een ander adres. Een canonical laat de pagina bereikbaar en geeft zoekmachines een voorkeur voor de hoofdversie van vergelijkbare inhoud.',href:'/website-migratie-checklist',link:'Bekijk de controlelijst bij een websiteverhuizing'},{question:'Waarom kiest Google toch een andere URL?',answer:'Een canonical is een signaal. Afwijkende links, redirects, inhoud en andere signalen kunnen tot een andere selectie leiden. Inspecteer beide URL’s voordat je opnieuw iets verandert.'}],
    next:['indexering-controleren','dubbele-metadata'],source:{label:'Google: dubbele URL’s samenvoegen',href:'https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls'}
  },
  'dubbele-metadata': {
    label:'Laat het verschil tussen pagina’s zien',
    answer:'Vergelijk bij dubbele titels of descriptions eerst de inhoud. Verschillende diensten verdienen een eigen beschrijving; technische varianten van dezelfde pagina vragen eerder om een consistente hoofd-URL. Alleen woorden wisselen lost inhoudelijke overlap niet op.',
    example:{title:'Twee diensten met één standaardtitel',before:'Zowel /webdesign als /onderhoud heeft “Welkom bij Voorbeeld — kwaliteit en service” als titel en dezelfde description.',decision:'De eerste pagina helpt bij een nieuwe website. De tweede legt het beheer na oplevering uit. Bezoekers stellen dus verschillende vragen.',after:'Benoem het eigen onderwerp: “Website laten maken | Voorbeeld” en “Websiteonderhoud: werkzaamheden en afspraken | Voorbeeld”. Laat elke description aansluiten op wat die pagina werkelijk uitlegt.'},
    steps:['Groepeer de identieke teksten en open de bijbehorende pagina’s naast elkaar.','Bepaal of het om verschillende onderwerpen of meerdere adressen voor dezelfde inhoud gaat.','Schrijf voor iedere echte pagina het onderwerp en de belangrijkste informatie in gewone taal. Houd merknaam en noodzakelijke context herkenbaar.','Controleer de uiteindelijke HTML én de zichtbare kop. Bekijk later in Search Console bij welke zoekvragen de pagina wordt vertoond; beoordeel niet alleen één handmatig zoekresultaat.'],
    pitfalls:'Een vaste lengte of een groene pluginmeter garandeert geen goede zoekresultaattekst. Herhaal niet in iedere titel een hele lijst diensten en plaatsnamen. Als de pagina nauwelijks eigen inhoud heeft, voeg dan eerst relevante uitleg toe of overweeg samenvoegen. Google kan titels en snippets anders samenstellen dan je invoer; dat is op zichzelf geen bewijs van een technische fout.',
    faqs:[{question:'Zijn identieke descriptions een straf van Google?',answer:'De melding bewijst geen straf. Het is een aanwijzing om te controleren of bezoekers de pagina’s uit elkaar kunnen houden en of er inhoudelijke overlap bestaat.'},{question:'Wat als Google mijn description niet toont?',answer:'Google kan een passage uit de pagina gebruiken die beter bij de zoekvraag past. Maak zowel je description als de zichtbare inhoud helder; één vaste weergave kun je niet afdwingen.'},{question:'Los ik dubbele pagina’s op met andere titels?',answer:'Niet als de rest van de inhoud dezelfde vraag op dezelfde manier beantwoordt. Onderzoek dan eerst welke pagina nodig is en welke URL als hoofdversie hoort te gelden.',href:'/tools/seo-audit/canonical-controleren',link:'Lees hoe je de hoofdversie controleert'}],
    next:['canonical-controleren','rapport-naar-actie'],source:{label:'Google: titellinks in zoekresultaten',href:'https://developers.google.com/search/docs/appearance/title-link'}
  },
  'afbeeldingen-en-alttekst': {
    label:'Beschrijf wat het beeld bijdraagt',
    answer:'Een goede alttekst geeft de relevante informatie of functie van een afbeelding door. Decoratie krijgt een lege alttekst. De audit vindt ontbrekende alt-attributen, maar kan niet bepalen of jouw beschrijving inhoudelijk juist is; daarvoor bekijk je het beeld in zijn context.',
    example:{title:'Een projectbeeld is meer dan een bestandsnaam',before:'Een screenshot van een mobiele reserveringspagina heeft de beschrijving “IMG_2048 website webdesign Venlo”.',decision:'Het beeld laat zien hoe een bezoeker een datum en tijd kiest. Dat is relevante informatie bij de toelichting op het ontwerp.',after:'Een passende beschrijving is bijvoorbeeld “Mobiele reserveringspagina met datumkeuze en beschikbare tijdsloten”. Staat dezelfde uitleg al volledig naast het beeld, voorkom dan onnodige herhaling.'},
    steps:['Bepaal eerst de functie: inhoud, decoratie, knop of link. Dezelfde afbeelding kan op twee plekken een andere functie hebben.','Beschrijf wat iemand moet weten als het beeld niet zichtbaar is. Een grafiek vraagt vaak ook een tekstuele conclusie of toegankelijke tabel naast het beeld.','Controleer klikbare afbeeldingen: is er zichtbare linktekst, of moet de alttekst het doel van de link benoemen?','Lees de pagina zonder beelden door en controleer belangrijke onderdelen met een schermlezer. Een audit zonder ontbrekende attributen is nog geen volledige toegankelijkheidsbeoordeling.'],
    pitfalls:'Vul lege altteksten niet automatisch met zoekwoorden of bestandsnamen. Daarmee kan decoratie juist ruis worden voor mensen die een schermlezer gebruiken. Scherpte, compressie en lazy loading zijn andere onderwerpen. Een groot beeld bovenaan moet bovendien niet onnodig wachten op scrollen; laadgedrag bepaal je op basis van de plaats en functie.',
    faqs:[{question:'Moet het woord “afbeelding” in de alttekst?',answer:'Meestal niet. Beschrijf de relevante inhoud. Benoem het type alleen als dat betekenis toevoegt, bijvoorbeeld een historische kaart of een schermafbeelding van een instelling.'},{question:'Kan de scan zien of een lege alttekst fout is?',answer:'Nee. De scan ziet het attribuut, maar begrijpt niet betrouwbaar de functie van het beeld in het ontwerp. Een bewust lege tekst wordt daarom niet automatisch als fout geteld.'},{question:'Maken altteksten mijn website sneller?',answer:'Nee. Daarvoor kijk je onder meer naar bestandsgrootte, afmetingen, responsive varianten en laadvolgorde. Een meting helpt je de echte oorzaak te vinden.',href:'/website-snelheid-testen',link:'Zo lees je een snelheidsmeting'}],
    next:['interne-links-controleren','rapport-naar-actie'],source:{label:'W3C: beslisboom voor alttekst',href:'https://www.w3.org/WAI/tutorials/images/decision-tree/'}
  },
  'rapport-naar-actie': {
    label:'Een rapport dat tot actie leidt',
    answer:'Orden bevindingen op het belang van de pagina, aantoonbaar bewijs en de gevolgen voor bezoekers. Herstel onbedoelde blokkades en kapotte hoofdroutes eerst. Beoordeel daarna inhoud en metadata. Controleer iedere wijziging opnieuw; een mooiere score is geen einddoel.',
    example:{title:'Van veertig meldingen naar drie werkpunten',before:'Twintig dienstenpagina’s hebben dezelfde onbedoelde noindex. Daarnaast zijn meerdere descriptions dubbel en is één contactlink kapot.',decision:'De noindex kan één templatefout zijn. De contactlink blokkeert een belangrijke taak. De descriptions verdienen inhoudelijke beoordeling na het herstel.',after:'Werkpunt 1: herstel de publieke template. Werkpunt 2: repareer en test de contactroute. Werkpunt 3: groepeer de metadata per onderwerp. Eén oorzaak kan veel meldingen tegelijk verklaren.'},
    steps:['Bewaar het meetmoment, de onderzochte URL’s en de beperkingen. Vergelijk een steekproef niet alsof de hele website is onderzocht.','Groepeer meldingen per mogelijke oorzaak, zoals een centrale domeininstelling of een gedeeld paginatemplate. Controleer die hypothese vóór je alles aanpast.','Leg per taak de eigenaar, wijziging en hercontrole vast. Benoem ook welke onderdelen bewust blijven zoals ze zijn.','Controleer de technische uitkomst na publicatie. Bekijk veranderingen in bezoek en aanvragen pas over een passende periode, met bron en context.'],
    pitfalls:'Een rode melding is niet altijd belangrijk voor jouw bedrijf; een onduidelijke dienst kan belangrijk zijn zonder technische foutmelding. Verwar daarnaast een uitgevoerde wijziging niet met een bewezen groei in aanvragen. Seizoen, campagnes en meettoestemming beïnvloeden cijfers. De Hub kan beschikbare bronnen en werkzaamheden naast elkaar laten zien, maar maakt ontbrekende data niet alsnog bekend.',
    faqs:[{question:'Moet ik alle meldingen oplossen vóór ik live ga?',answer:'Niet iedere melding is een blokkade. Belangrijke bereikbaarheid, onbedoelde indexuitsluiting en kapotte contactroutes verdienen wel directe controle. Leg voor overige punten vast waarom en wanneer je ze oppakt.'},{question:'Wanneer is een redesign zinvol?',answer:'Wanneer structuur, inhoud of gebruik op meerdere belangrijke routes niet meer aansluiten. Een enkele verkeerde canonical vraagt meestal om gericht herstel, niet om een complete nieuwe website.'},{question:'Kan Sitesnit de punten opvolgen?',answer:'Ja, we kunnen de uitkomst bespreken en bepalen welke werkzaamheden passen. Monitoring en het uitvoeren van verbeteringen spreken we afzonderlijk af.',href:'/diensten/website-monitoring',link:'Bekijk hoe Sitesnit Hub inzicht en werkzaamheden samenbrengt'}],
    next:['indexering-controleren','dubbele-metadata'],source:{label:'Google: een SEO-aanpak kiezen',href:'https://developers.google.com/search/docs/fundamentals/do-i-need-seo'}
  }
};
