/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.jsonc --env-file .dev.vars.example --env-interface UptimeWorkerEnv --strict-vars=false --include-runtime=false` (hash: 71245c8344ad9f2e3eff6c4db8913a5a)
interface __BaseEnv_UptimeWorkerEnv {
	UPTIME_ENABLED: string;
	UPTIME_MONITOR_ID: string;
	UPTIME_TARGETS_JSON: string;
	UPTIME_INGEST_URL: string;
	UPTIME_INGEST_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_UptimeWorkerEnv {}
}
interface UptimeWorkerEnv extends __BaseEnv_UptimeWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "UPTIME_ENABLED" | "UPTIME_MONITOR_ID" | "UPTIME_TARGETS_JSON" | "UPTIME_INGEST_URL" | "UPTIME_INGEST_SECRET">> {}
}
