import {hubMfaSchema} from './mfa';
/** Additive Hub tables. Authentication tables are generated by pinned Better Auth. */
export const hubSchema = hubMfaSchema + `
CREATE TABLE IF NOT EXISTS hub_clients (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS hub_sites (id TEXT PRIMARY KEY, client_id TEXT NOT NULL REFERENCES hub_clients(id), name TEXT NOT NULL, origin TEXT NOT NULL, created_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS hub_memberships (user_id TEXT NOT NULL, client_id TEXT NOT NULL REFERENCES hub_clients(id), PRIMARY KEY(user_id,client_id));
CREATE TABLE IF NOT EXISTS hub_admins (user_id TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS hub_invitations (token_hash TEXT PRIMARY KEY, email TEXT NOT NULL, client_id TEXT, role TEXT NOT NULL CHECK(role IN ('client','admin')), expires_at BIGINT NOT NULL, accepted_by TEXT, created_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS hub_integrations (site_id TEXT NOT NULL REFERENCES hub_sites(id), provider TEXT NOT NULL, config_json TEXT NOT NULL, PRIMARY KEY(site_id,provider));
CREATE TABLE IF NOT EXISTS hub_snapshots (site_id TEXT NOT NULL REFERENCES hub_sites(id), provider TEXT NOT NULL, payload_json TEXT NOT NULL, fetched_at BIGINT NOT NULL, expires_at BIGINT NOT NULL, error_code TEXT, PRIMARY KEY(site_id,provider));
CREATE TABLE IF NOT EXISTS hub_work_items (id TEXT PRIMARY KEY, site_id TEXT NOT NULL REFERENCES hub_sites(id), title TEXT NOT NULL, detail TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('open','in_progress','completed')), evidence TEXT NOT NULL, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS hub_monthly_reports (site_id TEXT NOT NULL REFERENCES hub_sites(id), month TEXT NOT NULL, summary TEXT NOT NULL, created_at BIGINT NOT NULL, PRIMARY KEY(site_id,month));
CREATE TABLE IF NOT EXISTS hub_uptime_checks (id TEXT PRIMARY KEY, site_id TEXT NOT NULL REFERENCES hub_sites(id), checked_at BIGINT NOT NULL, status TEXT NOT NULL CHECK(status IN ('up','down','unknown')), http_status INTEGER, latency_ms INTEGER, location TEXT, error_code TEXT);
CREATE INDEX IF NOT EXISTS hub_uptime_site_time ON hub_uptime_checks(site_id,checked_at);
CREATE TABLE IF NOT EXISTS hub_admin_log (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, action TEXT NOT NULL, site_id TEXT, created_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS hub_mail_usage (period TEXT PRIMARY KEY, count INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS hub_sync_locks (site_id TEXT NOT NULL, provider TEXT NOT NULL, owner TEXT NOT NULL, expires_at BIGINT NOT NULL, PRIMARY KEY(site_id,provider));
CREATE TABLE IF NOT EXISTS hub_site_sync_attempts (site_id TEXT PRIMARY KEY REFERENCES hub_sites(id), attempted_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS hub_uptime_deliveries (id TEXT PRIMARY KEY, received_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS hub_monitor_samples (site_id TEXT NOT NULL REFERENCES hub_sites(id), scheduled_at BIGINT NOT NULL, checked_at BIGINT NOT NULL, status TEXT NOT NULL, http_status INTEGER, latency_ms INTEGER, error_code TEXT, monitor_id TEXT NOT NULL, PRIMARY KEY(site_id,scheduled_at));
`;
